obj-$(CONFIG_ECNT_FLASH) += flash/
obj-$(CONFIG_ECNT_NET) += net/
obj-$(CONFIG_ECNT_BOOTARGS) += bootargs/
obj-$(CONFIG_ECNT_IMAGE) += image/
obj-$(CONFIG_ECNT_MULTIUPGRADE) += gpio.o
obj-$(CONFIG_ECNT_MULTIUPGRADE) += time.o
obj-$(CONFIG_ECNT) += ecnt_scu.o