obj-y :=  _arm_negdf2.o _arm_addsubdf3.o _arm_muldivdf3.o _arm_cmpdf2.o \
		_arm_unorddf2.o _arm_fixdfsi.o _arm_fixunsdfsi.o _arm_truncdfsf2.o \
		_arm_addsubsf3.o _arm_negsf2.o _arm_muldivsf3.o _arm_cmpsf2.o \
		_arm_unordsf2.o _arm_fixunssfsi.o _arm_fixsfsi.o \
		_aeabi_ldivmod.o _dvmd_lnx.o bpabi.o _divdi3.o _ashldi3.o _lshrdi3.o _udivdi3.o libc.a \
		softfloat.o 