#ifndef __UPGRADE_INFO_H__
#define __UPGRADE_INFO_H__

#ifdef INCLUDE_RECORD_UPGRADE_INFO

typedef enum _UPGRADE_STATUS
{
	/* For Cloud Firmware Version Check */
	UPGRADE_STATUS_CLOUD_FIRM_CHECKING = 2,
	UPGRADE_STATUS_CLOUD_FIRM_CHECK_SUCCESS = 3,
	UPGRADE_STATUS_CLOUD_FIRM_CHECK_FAILED = -4,

	/* For Cloud or Remote firmware server(like ACS) Firmware Download Failed */
	UPGRADE_STATUS_DOWNLOADING_FAILED = -2,
	UPGRADE_STATUS_CANT_ACCESS_DOWNLOAD_SERVER = -3,

	/* For Univeral Upgrading Status (Cloud/CWMP/Http) */
	UPGRADE_STATUS_UPGRADE_SUCCESS = 0,
	UPGRADE_STATUS_UPGRADING = 1,
	UPGRADE_STATUS_UPGRADE_FAILED = -1,
	UPGRADE_STATUS_END
} UPGRADE_STATUS;

#endif /*INCLUDE_RECORD_UPGRADE_INFO*/

#endif /*__UPGRADE_INFO_H__*/
