#!/bin/sh

cd $1

echo "mknod ..."

mknod dev/pppox_iptables c 220 0
mknod	dev/brcmboard   c 206 0
mknod	dev/bcmadsl0    c 208 0
mknod	dev/bdmf_shell c 215 0
if [ "x$INCLUDE_VOIP" = "xy" ]; then
mknod	dev/bcmendpoint0 c 209 0
mknod	dev/voip	c 214 0
mknod	dev/pcmshim0 	c 217 0
mknod	dev/ac97	c 222 0
mknod	dev/slac	c 223 0
mknod	dev/bcmprof	c 224 0
mknod	dev/si3215	c 225 0
fi
mknod	dev/bcmxtmcfg0	c 228 0
mknod	dev/bcmvlan     c 238 0
mknod   dev/pwrmngt     c 240 0	
mknod   dev/bcmfap      c 241 0
mknod   dev/fcache      c 242 0
mknod   dev/ingqos      c 243 0
mknod   dev/bpm         c 244 0
mknod   dev/bcmarl      c 245 0	
mknod   dev/gmac        c 249 0

mknod	dev/tms 	c 250 0
mknod	dev/bcmrdpa 	c 251 0
mknod	dev/pktrunner 	c 252 0

