/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file ipv6RouterAdvertTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef IPV6ROUTERADVERTTABLE_DATA_GET_H
#define IPV6ROUTERADVERTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ipv6RouterAdvertTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-MIB::ipv6RouterAdvertTable is subid 39 of ip.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.39, length: 8
*/
    /*
     * indexes
     */

    int ipv6RouterAdvertSendAdverts_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertSendAdverts_val_ptr );
    int ipv6RouterAdvertMaxInterval_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertMaxInterval_val_ptr );
    int ipv6RouterAdvertMinInterval_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertMinInterval_val_ptr );
    int ipv6RouterAdvertManagedFlag_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertManagedFlag_val_ptr );
    int ipv6RouterAdvertOtherConfigFlag_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertOtherConfigFlag_val_ptr );
    int ipv6RouterAdvertLinkMTU_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertLinkMTU_val_ptr );
    int ipv6RouterAdvertReachableTime_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertReachableTime_val_ptr );
    int ipv6RouterAdvertRetransmitTime_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertRetransmitTime_val_ptr );
    int ipv6RouterAdvertCurHopLimit_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertCurHopLimit_val_ptr );
    int ipv6RouterAdvertDefaultLifetime_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertDefaultLifetime_val_ptr );
    int ipv6RouterAdvertRowStatus_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertRowStatus_val_ptr );


int ipv6RouterAdvertTable_indexes_set_tbl_idx(ipv6RouterAdvertTable_mib_index *tbl_idx, long ipv6RouterAdvertIfIndex_val);
int ipv6RouterAdvertTable_indexes_set(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, long ipv6RouterAdvertIfIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* IPV6ROUTERADVERTTABLE_DATA_GET_H */
/** @} */
