/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef IPV6ROUTERADVERTTABLE_DATA_ACCESS_H
#define IPV6ROUTERADVERTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ipv6RouterAdvertTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-MIB::ipv6RouterAdvertTable is subid 39 of ip.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.39, length: 8
*/


    int ipv6RouterAdvertTable_init_data(ipv6RouterAdvertTable_registration * ipv6RouterAdvertTable_reg);


    /*
     * TODO:180:o: Review ipv6RouterAdvertTable cache timeout.
     * The number of seconds before the cache times out
     */
#define IPV6ROUTERADVERTTABLE_CACHE_TIMEOUT   60

void ipv6RouterAdvertTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void ipv6RouterAdvertTable_container_shutdown(netsnmp_container *container_ptr);

int ipv6RouterAdvertTable_container_load(netsnmp_container *container);
void ipv6RouterAdvertTable_container_free(netsnmp_container *container);

int ipv6RouterAdvertTable_cache_load(netsnmp_container *container);
void ipv6RouterAdvertTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int ipv6RouterAdvertTable_row_prep( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);

int ipv6RouterAdvertTable_validate_index( ipv6RouterAdvertTable_registration * ipv6RouterAdvertTable_reg,
                               ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);
int ipv6RouterAdvertIfIndex_check_index( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx ); /* internal */


#ifdef __cplusplus
}
#endif

#endif /* IPV6ROUTERADVERTTABLE_DATA_ACCESS_H */
