#!/bin/bash
SNMP_DIR=$(pwd)
OPSSL_DIR=$SNMP_DIR/OPSSL

#Do the configuration before compiling
#####################################
#	Config the host environment		#
#####################################
echo "Config the host environment"
if [ "$COMPILE_TOOLCHAIN" = "mips-linux" ] ;then
	echo "Build 3162 SNMP"
	HOST="'--host=mips-linux' 'CC=mips-linux-gcc' '--with-endianness=big' '--with-ar=mips-linux-ar' 'host_alias=mips-linux'"
fi

if [ "$COMPILE_TOOLCHAIN" = "mips-linux-uclibc" ] ;then
	echo "Build 3262 SNMP"
	HOST="'--host=mips-linux-gnu' 'CC=mips-linux-uclibc-gcc' '--with-endianness=big' '--with-ar=mips-linux-uclibc-ar' 'host_alias=mips-linux-gnu'"
fi

if [ "$COMPILE_TOOLCHAIN" = "mips-unknown-linux-uclibc" ] ;then
	echo "Build 3262 SNMP"
	HOST="'--host=mips-linux-gnu' 'CC=mips-unknown-linux-uclibc-gcc' '--with-endianness=big' '--with-ar=mips-unknown-linux-uclibc-ar' 'host_alias=mips-linux-gnu'"
fi

if [ "$COMPILE_TOOLCHAIN" = "mips-buildroot-linux-uclibc" ] ;then
	echo "Build GCC4_6_UCLIBC SNMP"
	HOST="'--host=mips-linux' 'CC=mips-buildroot-linux-uclibc-gcc' '--with-endianness=big' '--with-ar=mips-buildroot-linux-uclibc-ar' 'host_alias=mips-linux'"
fi

#####################################
#	Config the compile flag:CFGLGS	#
#####################################
echo "Config the TCSUPPORT Option"
CFLAGS="-O2 -Wall -DTRENDCHIP"
if [ "$COMPILE_TOOLCHAIN" = "mips-buildroot-linux-uclibc" ] ;then
	CFLAGS="$CFLAGS -mips32r2 -msoft-float"
fi

if [ "$COMPILE_TOOLCHAIN" = "mips-linux-uclibc" ] ;then
	CFLAGS="$CFLAGS -mips32r2 -msoft-float"
fi

if [ "$TCSUPPORT_SNMP_FULL" != "" ] ;then
	CFLAGS="$CFLAGS -DTCSUPPORT_SNMP_FULL"
	echo "Bulid Full Snmp"

#only Full support trap & snmnpv3
if [ "$TCSUPPORT_START_TRAP" != "" ] ;then
	CFLAGS="$CFLAGS -DTCSUPPORT_START_TRAP"
fi

if [ "$TCSUPPORT_SNMP_CHT" != "" ] ;then
	CFLAGS="$CFLAGS -DTCSUPPORT_SNMP_CHT"
fi

if [ "$TCSUPPORT_SNMP_V3" != "" ] ;then
	CFLAGS="$CFLAGS -DTSUPPORT_SNMP_V3"
fi
fi

if [ "$TCSUPPORT_SNMP_TRUSTIP" != "" ] ;then
	CFLAGS="$CFLAGS -DTCSUPPORT_SNMP_TRUSTIP"
fi

if [ "$TCSUPPORT_IPV6_SNMP" != "" ] ;then
	CFLAGS="$CFLAGS -DTCSUPPORT_IPV6_SNMP"
fi

#Custom Compile Option
if [ "$TCSUPPORT_C1_OBM" != "" ] ;then
	CFLAGS="$CFLAGS -DTCSUPPORT_C1_OBM"
fi

if [ "$TCSUPPORT_C1_ZY" != "" ] ;then
	CFLAGS="$CFLAGS -DTCSUPPORT_C1_ZY_HGU"
fi

echo "$CFLAGS"

#####################################
#	Config the SNMP modules			#
#####################################
echo "Config the snmp moudles"
WITHOUT_MODULES="ucd_snmp agent_mibs agentx host disman/schedule disman/event disman/event-mib smux"
WITH_MODULES="mibII/at mibII/ifTable mibII/ip mibII/tcp mibII/icmp mibII/udp"

if [ "$TCSUPPORT_SNMP_REDUCED" != "" ] ;then
	WITHOUT_MODULES="$WITHOUT_MODULES mibII/vacm_vars mibII/vacm_context target"
else
	WITH_MODULES="$WITH_MODULES mibII/vacm_vars mibII/vacm_context target"
fi
#only Full include trap
if [ "$TCSUPPORT_SNMP_FULL" != "" ] ;then
	WITH_MODULES="$WITH_MODULES notification notification/snmpNotifyTable notification-log-mib examples/notification"
else
	WITHOUT_MODULES="$WITHOUT_MODULES notification notification/snmpNotifyTable notification-log-mib"
fi
	
if [ "$TCSUPPORT_SNMP_V3" != "" ] ;then
#	default include snmpv3mibs module
#	WITH_MODULES="$WITH_MODULES "	
	echo "SUPPORT SNMPv3"
else
	WITHOUT_MODULES="$WITHOUT_MODULES snmpv3mibs"
fi

WITH_MODULES="$WITH_MODULES ip-mib"
echo "$WITH_MODULES"
#####################################
#	Config the SNMP option			#
#####################################
echo "config the snmp option"
OPTION="'--prefix=$SNMP_DIR/install_dir' '--disable-shared' '--disable-applications' '--enable-debugging' '--without-rpm' '--disable-snmptrapd-subagent' '--with-out-transports=TCP TCPIPv6 Callback Unix' '--enable-mini-agent' '--without-kmem-usage' '--disable-mib-loading' '--with-sys-contact=econet' '--with-sys-location=taiwan' '--with-logfile=/var/log/snmpd.log' '--with-persistent-directory=/etc/net-snmp'"

#Support SNMPv3
if [ "$TCSUPPORT_SNMP_V3" != "" ] ;then
	OPTION="$OPTION '--with-default-snmp-version=3' '--with-openssl=$OPSSL_DIR' '--datadir=/etc/net-snmp'"
else
	OPTION="$OPTION '--disable-des' '--disable-privacy' '--disable-md5' '--with-default-snmp-version=2'"
fi

#Support IPv6
if [ "$TCSUPPORT_IPV6_SNMP" != "" ] ;then
	OPTION="$OPTION '--with-transports=UDPIPv6' '--enable-ipv6'"
fi

#####################################
#	Create the config file			#
#####################################
echo "create the config file"
rm -f ./snmp_config
echo "./configure $HOST 'CFLAGS=$CFLAGS' '--with-out-mib-modules=$WITHOUT_MODULES' '--with-mib-modules=$WITH_MODULES' $OPTION " >./snmp_config
chmod 777 ./snmp_config
./snmp_config
echo 'Configuration has been done successfully.'

#Replacing the Makefile generated by configuration
#cp ../code_reduce_patch/net-snmp-5.3.1/agent.Makefile agent/
#cp ../code_reduce_patch/net-snmp-5.3.1/agent.helpers.Makefile agent/helpers/
#cp ../code_reduce_patch/net-snmp-5.3.1/snmplib.Makefile snmplib/

#Remove the last line of agent/mibgroup/mib_module_inits.h generated by configuration
#sed '$d' agent/mibgroup/mib_module_inits.h > agent/mibgroup/mib_module_inits.h.bak
#rm agent/mibgroup/mib_module_inits.h
#mv agent/mibgroup/mib_module_inits.h.bak agent/mibgroup/mib_module_inits.h
echo 'Starting to make...'

#Start to make clean and make
make clean; 
make
if [ ! -f agent/snmpd ] ; then
   cd ..
   exit 1
fi
mips-linux-strip agent/snmpd
echo 'make is finished successfully.' 
