OBJ_TARGET= _fixdfdi.o _fixsfdi.o _arm_cmpdf2.o _arm_addsubdf3.o \
		_arm_cmpsf2.o _fixunsdfdi.o  _fixunssfdi.o _arm_muldivdf3.o \
		_arm_fixunsdfsi.o _arm_truncdfsf2.o _arm_addsubsf3.o _arm_muldivsf3.o \
		_arm_fixunssfsi.o _arm_fixdfsi.o _arm_fixsfsi.o 
ifeq ($(strip $(TCSUPPORT_5_4_KERNEL)),)
OBJ_TARGET+= _aeabi_ldivmod.o _dvmd_lnx.o bpabi.o _divdi3.o _udivdi3.o libc.a 
endif
OBJ_TARGET+= softfloat.o 

obj-y := $(OBJ_TARGET)
