/* This file is automatically generated by configure.  Do not modify by hand. */
/* Define if compiling with the default_modules module files.  */
#define USING_DEFAULT_MODULES_MODULE 1
 
/* Define if compiling with the examples/notification module files.  */
#define USING_EXAMPLES_NOTIFICATION_MODULE 1
 
/* Define if compiling with the ip-mib module files.  */
#define USING_IP_MIB_MODULE 1
 
/* Define if compiling with the mibII/at module files.  */
#define USING_MIBII_AT_MODULE 1
 
/* Define if compiling with the mibII/icmp module files.  */
#define USING_MIBII_ICMP_MODULE 1
 
/* Define if compiling with the mibII/ifTable module files.  */
#define USING_MIBII_IFTABLE_MODULE 1
 
/* Define if compiling with the mibII/ip module files.  */
#define USING_MIBII_IP_MODULE 1
 
/* Define if compiling with the mibII/tcp module files.  */
#define USING_MIBII_TCP_MODULE 1
 
/* Define if compiling with the mibII/udp module files.  */
#define USING_MIBII_UDP_MODULE 1
 
/* Define if compiling with the mibII/vacm_context module files.  */
#define USING_MIBII_VACM_CONTEXT_MODULE 1
 
/* Define if compiling with the mibII/vacm_vars module files.  */
#define USING_MIBII_VACM_VARS_MODULE 1
 
/* Define if compiling with the notification module files.  */
#define USING_NOTIFICATION_MODULE 1
 
/* Define if compiling with the notification-log-mib module files.  */
#define USING_NOTIFICATION_LOG_MIB_MODULE 1
 
/* Define if compiling with the notification/snmpNotifyTable module files.  */
#define USING_NOTIFICATION_SNMPNOTIFYTABLE_MODULE 1
 
/* Define if compiling with the target module files.  */
#define USING_TARGET_MODULE 1
 
/* Define if compiling with the snmpv3mibs module files.  */
#define USING_SNMPV3MIBS_MODULE 1
 
/* Define if compiling with the mibII/snmp_mib module files.  */
#define USING_MIBII_SNMP_MIB_MODULE 1
 
/* Define if compiling with the mibII/system_mib module files.  */
#define USING_MIBII_SYSTEM_MIB_MODULE 1
 
/* Define if compiling with the mibII/sysORTable module files.  */
#define USING_MIBII_SYSORTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressTable module files.  */
#define USING_IP_MIB_IPADDRESSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressPrefixTable module files.  */
#define USING_IP_MIB_IPADDRESSPREFIXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/inetNetToMediaTable module files.  */
#define USING_IP_MIB_INETNETTOMEDIATABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipSystemStatsTable module files.  */
#define USING_IP_MIB_IPSYSTEMSTATSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ip_scalars module files.  */
#define USING_IP_MIB_IP_SCALARS_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6InterfaceTable module files.  */
#define USING_IP_MIB_IPV6INTERFACETABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6ScopeZoneIndexTable module files.  */
#define USING_IP_MIB_IPV6SCOPEZONEINDEXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6RouterAdvertTable module files.  */
#define USING_IP_MIB_IPV6ROUTERADVERTTABLE_MODULE 1
 
/* Define if compiling with the mibII/kernel_linux module files.  */
#define USING_MIBII_KERNEL_LINUX_MODULE 1
 
/* Define if compiling with the if-mib/ifTable module files.  */
#define USING_IF_MIB_IFTABLE_MODULE 1
 
/* Define if compiling with the mibII/ipAddr module files.  */
#define USING_MIBII_IPADDR_MODULE 1
 
/* Define if compiling with the mibII/var_route module files.  */
#define USING_MIBII_VAR_ROUTE_MODULE 1
 
/* Define if compiling with the mibII/route_write module files.  */
#define USING_MIBII_ROUTE_WRITE_MODULE 1
 
/* Define if compiling with the mibII/tcpTable module files.  */
#define USING_MIBII_TCPTABLE_MODULE 1
 
/* Define if compiling with the mibII/udpTable module files.  */
#define USING_MIBII_UDPTABLE_MODULE 1
 
/* Define if compiling with the util_funcs/header_generic module files.  */
#define USING_UTIL_FUNCS_HEADER_GENERIC_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_MODULE 1
 
/* Define if compiling with the notification/snmpNotifyFilterProfileTable module files.  */
#define USING_NOTIFICATION_SNMPNOTIFYFILTERPROFILETABLE_MODULE 1
 
/* Define if compiling with the notification-log-mib/notification_log module files.  */
#define USING_NOTIFICATION_LOG_MIB_NOTIFICATION_LOG_MODULE 1
 
/* Define if compiling with the header_complex module files.  */
#define USING_HEADER_COMPLEX_MODULE 1
 
/* Define if compiling with the target/target_counters_5_5 module files.  */
#define USING_TARGET_TARGET_COUNTERS_5_5_MODULE 1
 
/* Define if compiling with the target/snmpTargetAddrEntry module files.  */
#define USING_TARGET_SNMPTARGETADDRENTRY_MODULE 1
 
/* Define if compiling with the target/snmpTargetParamsEntry module files.  */
#define USING_TARGET_SNMPTARGETPARAMSENTRY_MODULE 1
 
/* Define if compiling with the target/target module files.  */
#define USING_TARGET_TARGET_MODULE 1
 
/* Define if compiling with the snmpv3/snmpMPDStats_5_5 module files.  */
#define USING_SNMPV3_SNMPMPDSTATS_5_5_MODULE 1
 
/* Define if compiling with the snmpv3/usmStats_5_5 module files.  */
#define USING_SNMPV3_USMSTATS_5_5_MODULE 1
 
/* Define if compiling with the snmpv3/snmpEngine module files.  */
#define USING_SNMPV3_SNMPENGINE_MODULE 1
 
/* Define if compiling with the snmpv3/usmUser module files.  */
#define USING_SNMPV3_USMUSER_MODULE 1
 
/* Define if compiling with the mibII/updates module files.  */
#define USING_MIBII_UPDATES_MODULE 1
 
/* Define if compiling with the util_funcs module files.  */
#define USING_UTIL_FUNCS_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressTable/ipAddressTable module files.  */
#define USING_IP_MIB_IPADDRESSTABLE_IPADDRESSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressPrefixTable/ipAddressPrefixTable module files.  */
#define USING_IP_MIB_IPADDRESSPREFIXTABLE_IPADDRESSPREFIXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable/ipDefaultRouterTable module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_IPDEFAULTROUTERTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/arp module files.  */
#define USING_IP_MIB_DATA_ACCESS_ARP_MODULE 1
 
/* Define if compiling with the ip-mib/inetNetToMediaTable/inetNetToMediaTable module files.  */
#define USING_IP_MIB_INETNETTOMEDIATABLE_INETNETTOMEDIATABLE_MODULE 1
 
/* Define if compiling with the ip-mib/inetNetToMediaTable/inetNetToMediaTable_interface module files.  */
#define USING_IP_MIB_INETNETTOMEDIATABLE_INETNETTOMEDIATABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/inetNetToMediaTable/inetNetToMediaTable_data_access module files.  */
#define USING_IP_MIB_INETNETTOMEDIATABLE_INETNETTOMEDIATABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/systemstats module files.  */
#define USING_IP_MIB_DATA_ACCESS_SYSTEMSTATS_MODULE 1
 
/* Define if compiling with the ip-mib/ipSystemStatsTable/ipSystemStatsTable module files.  */
#define USING_IP_MIB_IPSYSTEMSTATSTABLE_IPSYSTEMSTATSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipSystemStatsTable/ipSystemStatsTable_interface module files.  */
#define USING_IP_MIB_IPSYSTEMSTATSTABLE_IPSYSTEMSTATSTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipSystemStatsTable/ipSystemStatsTable_data_access module files.  */
#define USING_IP_MIB_IPSYSTEMSTATSTABLE_IPSYSTEMSTATSTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/scalars_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_SCALARS_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6InterfaceTable/ipv6InterfaceTable module files.  */
#define USING_IP_MIB_IPV6INTERFACETABLE_IPV6INTERFACETABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6ScopeZoneIndexTable/ipv6ScopeZoneIndexTable module files.  */
#define USING_IP_MIB_IPV6SCOPEZONEINDEXTABLE_IPV6SCOPEZONEINDEXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable/ipIfStatsTable module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_IPIFSTATSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable/ipIfStatsTable_interface module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_IPIFSTATSTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable/ipIfStatsTable_data_access module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_IPIFSTATSTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable module files.  */
#define USING_IP_MIB_IPV6ROUTERADVERTTABLE_IPV6ROUTERADVERTTABLE_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_SNMPNOTIFYFILTERTABLE_MODULE 1
 
/* Define if compiling with the util_funcs/header_simple_table module files.  */
#define USING_UTIL_FUNCS_HEADER_SIMPLE_TABLE_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressTable/ipAddressTable_interface module files.  */
#define USING_IP_MIB_IPADDRESSTABLE_IPADDRESSTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressTable/ipAddressTable_data_access module files.  */
#define USING_IP_MIB_IPADDRESSTABLE_IPADDRESSTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressPrefixTable/ipAddressPrefixTable_interface module files.  */
#define USING_IP_MIB_IPADDRESSPREFIXTABLE_IPADDRESSPREFIXTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressPrefixTable/ipAddressPrefixTable_data_access module files.  */
#define USING_IP_MIB_IPADDRESSPREFIXTABLE_IPADDRESSPREFIXTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/defaultrouter module files.  */
#define USING_IP_MIB_DATA_ACCESS_DEFAULTROUTER_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable/ipDefaultRouterTable_interface module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_IPDEFAULTROUTERTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable/ipDefaultRouterTable_data_access module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_IPDEFAULTROUTERTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable/ipDefaultRouterTable_data_get module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_IPDEFAULTROUTERTABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/arp_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_ARP_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/arp_netlink module files.  */
#define USING_IP_MIB_DATA_ACCESS_ARP_NETLINK_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/systemstats_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_SYSTEMSTATS_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/systemstats_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_SYSTEMSTATS_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/scalars_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_SCALARS_LINUX_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable_interface module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable_data_access module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6InterfaceTable/ipv6InterfaceTable_interface module files.  */
#define USING_IP_MIB_IPV6INTERFACETABLE_IPV6INTERFACETABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6InterfaceTable/ipv6InterfaceTable_data_access module files.  */
#define USING_IP_MIB_IPV6INTERFACETABLE_IPV6INTERFACETABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipv6scopezone module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPV6SCOPEZONE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6ScopeZoneIndexTable/ipv6ScopeZoneIndexTable_interface module files.  */
#define USING_IP_MIB_IPV6SCOPEZONEINDEXTABLE_IPV6SCOPEZONEINDEXTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6ScopeZoneIndexTable/ipv6ScopeZoneIndexTable_data_access module files.  */
#define USING_IP_MIB_IPV6SCOPEZONEINDEXTABLE_IPV6SCOPEZONEINDEXTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable/ipIfStatsTable_data_get module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_IPIFSTATSTABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable_interface module files.  */
#define USING_IP_MIB_IPV6ROUTERADVERTTABLE_IPV6ROUTERADVERTTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable_data_access module files.  */
#define USING_IP_MIB_IPV6ROUTERADVERTTABLE_IPV6ROUTERADVERTTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable_data_get module files.  */
#define USING_IP_MIB_IPV6ROUTERADVERTTABLE_IPV6ROUTERADVERTTABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable_data_set module files.  */
#define USING_IP_MIB_IPV6ROUTERADVERTTABLE_IPV6ROUTERADVERTTABLE_DATA_SET_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable_interface module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_SNMPNOTIFYFILTERTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable_data_access module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_SNMPNOTIFYFILTERTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface_linux module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_LINUX_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface_ioctl module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_IOCTL_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/defaultrouter_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_DEFAULTROUTER_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/defaultrouter_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_DEFAULTROUTER_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipv6scopezone_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPV6SCOPEZONE_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipv6scopezone_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPV6SCOPEZONE_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_ioctl module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_IOCTL_MODULE 1
 
