
#export BSP_INT_INSTALL=$(BSP_ROOTDIR)/install_bsp_exclusive

#export BSP_INT_INC=$(BSP_INT_INSTALL)/inc
#export BSP_INT_FS=$(BSP_INT_INSTALL)/fs
#export BSP_INT_LIB=$(BSP_INT_FS)/lib
#export BSP_INT_FS_USEFS=$(BSP_INT_FS)/userfs/bin


export BSP_PRIVATEDIR=$(BSP_ROOTDIR)/private
export BSP_PUBLICDIR=$(BSP_ROOTDIR)/public
export BSP_API_DIR=$(BSP_PRIVATEDIR)/API

ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
export APP_BSP_EXCLUSIVE_DIR=$(PKG_BUILD_DIR)/private_exclusive
export APP_BSP_EXCLUSIVE_PUBLIC_DIR=$(PKG_BUILD_DIR)/public_exclusive
export APP_BSP_EXCLUSIVE_PRIVATE_DIR=$(PKG_BUILD_DIR)/private_exclusive
export APP_BSP_BRCTL_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/bridge-utils-1.5
export APP_BSP_TCCI_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/tcci_bsp
endif

export BSP_API_MTK_ITF_DIR=$(BSP_API_DIR)/mtk_itf
export BSP_API_MTK_ITF_QOS_DIR = $(BSP_API_MTK_ITF_DIR)/mtk_itf_qos
export BSP_API_MTK_ITF_SWITCH_DIR = $(BSP_API_MTK_ITF_DIR)/mtk_itf_switch
export BSP_API_MTK_ITF_FE_DIR=$(BSP_API_MTK_ITF_DIR)/mtk_itf_fe
export BSP_API_MTK_ITF_SIMULATION_DIR=$(BSP_API_MTK_ITF_DIR)/mtk_itf_simulation
export BSP_API_MTK_ITF_PPE_DIR=$(BSP_API_MTK_ITF_DIR)/mtk_itf_ppe

ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
ifneq ($(strip $(TCSUPPORT_4_4_KERNEL)),)
KERNEL_DIR:=$(KERNEL_ROOT)/linux-4.4.115
KERNEL_HEADER:=$(KERNEL_DIR)/usr/include
endif
ifneq ($(strip $(TCSUPPORT_5_4_KERNEL)),)
KERNEL_DIR:=$(KERNEL_ROOT)/linux-5.4.55
KERNEL_HEADER:=$(KERNEL_DIR)/usr/include
endif
endif

ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
COMPILEOPTION_CFLAGS := 
export COMPILEOPTION_CFLAGS
COMPILEOPTION_LDFLAGS := -lcompileoption
export COMPILEOPTION_LDFLAGS
endif

ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
LIB_INSTALL_DIR:=$(APP_BSP_DIR)/bsp_lib
FILESYSTEM_DIR:=$(APP_BSP_DIR)/bsp_fs
LIBINSTALL_LDFLAGS:=-L$(LIB_INSTALL_DIR)
LIBINSTALL_CFLAGS:=-I$(LIB_INSTALL_DIR)
APP_BSP_LIB_DIR:=$(LIB_INSTALL_DIR)
APP_API_LIB_OUTPUT_DIR:=$(LIB_INSTALL_DIR)
export APP_API_LIB_OUTPUT_DIR
APP_BSP_API_LIB_OUTPUT_DIR:=$(APP_BSP_LIB_DIR)
export APP_BSP_API_LIB_OUTPUT_DIR
else
APP_BSP_LIB_DIR:=$(LIB_INSTALL_DIR)
APP_API_LIB_OUTPUT_DIR:=$(LIB_INSTALL_DIR)
export APP_API_LIB_OUTPUT_DIR
APP_BSP_API_LIB_OUTPUT_DIR:=$(APP_BSP_LIB_DIR)
export APP_BSP_API_LIB_OUTPUT_DIR
endif

export BSP_API_CPUTEMP_DIR=$(BSP_PRIVATEDIR)/cpu_temp
export BSP_API_TCWDOG_DIR=$(BSP_PRIVATEDIR)/tcwdog
export BSP_API_PWCTLCMD_DIR=$(BSP_PRIVATEDIR)/pwctlcmd

export BSP_API_11KV_DIR=$(BSP_PRIVATEDIR)/11kv_test_daemon
ifneq ($(strip $(TCSUPPORT_ATED_V2)),)
export BSP_API_ATED_DIR=$(BSP_PRIVATEDIR)/ATED_v2
else
export BSP_API_ATED_DIR=$(BSP_PRIVATEDIR)/ATED
endif
export BSP_API_BNDSTRG_DIR=$(BSP_PRIVATEDIR)/bndstrg_plus
export BSP_API_WLANCMD_DIR=$(BSP_PRIVATEDIR)/wlancmd
export BSP_API_MTKIAPPD_DIR=$(BSP_PRIVATEDIR)/mtkiappd
export BSP_API_IWPRIVGET_DIR=$(BSP_PRIVATEDIR)/iwprivget

export BSP_API_8021X_DIR=$(BSP_PUBLICDIR)/8021X
export BSP_API_WRIELESSTOOL_DIR=$(BSP_PUBLICDIR)/wireless_tools.28

export BSP_APP_MTD_DIR=$(BSP_PUBLICDIR)/mtd
export BSP_APP_IPROUTE_IP_NEW_DIR=$(BSP_PUBLICDIR)/iproute2-4.4.0
export BSP_APP_OPENSSL_DIR=$(BSP_PUBLICDIR)/openssl-1.0.1p
export BSP_APP_OVS_DIR=$(BSP_PUBLICDIR)/openvswitch-2.5.0
#for app_bsp/api
export APP_BSP_SMUXCTL_DIR=$(BSP_PRIVATEDIR)/smuxctl
export APP_BSP_ETC_SCRIPT_DIR=$(BSP_PRIVATEDIR)/etc_script
export APP_BSP_PORTBIND_DIR=$(BSP_PRIVATEDIR)/portbindcmd

export APP_BSP_MTD_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/mtd

####################################################################################
# sub-class of APP_BSP_DIR=$(TRUNK_DIR)/app_bsp and BSP_ROOTDIR
export APP_BSP_BUILD_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/bsp_builder
APP_BSP_EXCLUSIVE_PUBLIC_8021X_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/8021X
ifneq ($(strip $(TCSUPPORT_BUSYBOX_1_26_2)),)
    APP_BSP_BUSYBOX_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/busybox-1.26.2
else
    APP_BSP_BUSYBOX_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/busybox-1.00
endif
APP_BSP_PPPD_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/ppp-2.4.7
APP_BSP_BRCTL_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/bridge-utils-1.5
APP_BSP_IPTABLES_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/iptables-1.6.1
APP_BSP_IPTABLES_INSTALL_DIR=$(APP_BSP_IPTABLES_DIR)/install
APP_BSP_BR2684_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/br2684ctl
APP_BSP_WRIELESSTOOL_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/wireless_tools.28
ECNT_EVENT_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_event
APP_BSP_MXML_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/mxml-2.4
APP_OMCI_DEMO_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/omci_demo
APP_BSP_TCCI_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/tcci_bsp
APP_BSP_ATED_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/ATED
APP_BSP_11KV_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/11kv_test_daemon
APP_BSP_BNDSTRG_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/bndstrg_plus
APP_BSP_WLANCMD_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/wlancmd
APP_BSP_TCWDOG_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/tcwdog
APP_BSP_SMUX_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/smuxctl
APP_BSP_ETHTOOL_DIR=$(APP_BSP_PRIVATEDIR)/ethtool
APP_BSP_INIT_SCRIPT_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/init_script
APP_BSP_IGMP_PROXY_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/igmpproxy-0.1
APP_BSP_MLD_PROXY_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/ecmh-2005.02.09
APP_BSP_EBTABLES_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/ebtables-v2.0.8-2

export BSP_BLAPI_DIR=$(BSP_API_DIR)/ecnt_blapi
