# This derives from the main Ubuntu config
lxc.include = /proj/mtk19274/W/tclinux_phoenix/apps/public/joyme2.0/install_lxclib/share/lxc/config/ubuntu.common.conf

lxc.hook.clone = /proj/mtk19274/W/tclinux_phoenix/apps/public/joyme2.0/install_lxclib/share/lxc/hooks/ubuntu-cloud-prep
