#ifndef _NPU_TEST_COMMON_H
#define _NPU_TEST_COMMON_H
#ifdef TCSUPPORT_CPU_EN7523
#define MAX_CORE_NUM    (4) 
#else
#define MAX_CORE_NUM    (8) 
#endif
#define MBOX_IRQ_TEST_NUM MAX_CORE_NUM
#define MAX_Q_SIZE	(8)
#define MAX_ARRAY_SIZE    (8) 
#define MDELAY_TEST_CNT (1000)
#define ALL_FF  (0xffffffff)
#define CSR_PC_BASE_ADDR	(0xbec08800)
#define CSR_REG_NUM		(12)

enum tCases {
    TEST_NONE=0,
    TEST_THREAD_Q_FULL, /*1*/
    TEST_THREAD_Q_OVERFULL,
    TEST_THREAD_PRIORITY, /*3*/
    TEST_THREAD_JOIN,
    TEST_THREAD_CORE1_MASTER, /*5*/
    TEST_MUTEX_ONE_BLK_TYPE,
    TEST_MUTEX_TWO_BLK_TYPE,
    TEST_MUTEX_ONE_REG_TYPE, /*8*/
    TEST_MUTEX_TWO_REG_TYPE,
    TEST_MUTEX_ONE_BLK_REG_TYPE, /*10*/
    TEST_MUTEX_64,
    TEST_MUTEX_NOT_OWNER_UNLOCK,
    TEST_MUTEX_TRYLOCK, /*13*/
    TEST_MUTEX_SIGNAL,
    TEST_IPC_THREAD_API, /*15*/
    TEST_IPC_MUTEX_API,
    TEST_UNC_ACCESS_RAMS,
    TEST_CAC_ACCESS_RAMS, /*18*/
    TEST_READ_STARVING,
    TEST_READ_PERF, /*20*/
    TEST_PLIC_EL_TRIG,
    TEST_PLIC_PRIORITY,
    TEST_PLIC_THRESHOLD, /*23*/
    TEST_PLIC_ISR_PERF,
    TEST_MBOX_INTR, /*25*/
    TEST_MBOX_RW_REGS,
    TEST_NPU_TIMER,
    TEST_NPU_WDOG, /*28*/
    TEST_NPU_CPUTMR,
    TEST_NPU_RESET, /*30*/
    TEST_PER_CORE_LOCK,
    TEST_MULTI_CORE_LOCK,
    TEST_CORE_ON_OFF, /*33*/
    TEST_HANG_CORE_CSR,
    TEST_DEAD_CORE_CSR, /*35*/
    TEST_EXCEP_CORE_CSR,
    TEST_PLIC_RESET,
    TEST_HW_KERN_RESET, /*38*/
	TEST_HW_KERN_RESET_2,
	TEST_WT_DRAM_STARVING, /*40*/
    TEST_HOST_L2C_SRAM,
    TEST_NPU_AS_DMA,
    TEST_NPU_DRAM_COHERENCE, /*43*/
    TEST_NPU_RW_L2C_SRAM,
	TEST_NPU_BLOCK_CNT,
	TEST_NPU_TZPC_MULTI_ISSUE,
	TEST_NPU_RBUS_STRESS,
	TEST_NPU_CPU_ACCESS, /*48*/
    TEST_LAST_ITEM /* the last one */
};

#endif

