#ifndef	__HW_NAT_NPU_TUNNLE_OFFLOAD_H__
#define	__HW_NAT_NPU_TUNNLE_OFFLOAD_H__

typedef enum
{
    NPU_UDF_START = 0,
    NPU_UDF_VXLAN_0,
    NPU_UDF_VXLAN_1,
    NPU_UDF_VXLAN_2,
    NPU_UDF_VXLAN_3,
    NPU_UDF_VXLAN_4,
    NPU_UDF_VXLAN_5,
    NPU_UDF_VXLAN_6,
    NPU_UDF_VXLAN_7,
    NPU_UDF_VXLAN_8,
    NPU_UDF_VXLAN_9,
    NPU_UDF_VXLAN_10,
    NPU_UDF_VXLAN_11,
    NPU_UDF_VXLAN_12,
    NPU_UDF_VXLAN_13,
    NPU_UDF_VXLAN_14,
    NPU_UDF_VXLAN_15,
    NPU_UDF_VXLAN_16,
    NPU_UDF_VXLAN_17,
    NPU_UDF_VXLAN_18,
    NPU_UDF_VXLAN_19, /*20*/    
    NPU_UDF_VXLAN_DOWN_0,
    NPU_UDF_VXLAN_DOWN_1,
    NPU_UDF_VXLAN_DOWN_2,
    NPU_UDF_VXLAN_DOWN_3,
    NPU_UDF_VXLAN_DOWN_4,
    NPU_UDF_VXLAN_DOWN_5,
    NPU_UDF_VXLAN_DOWN_6,
    NPU_UDF_VXLAN_DOWN_7,
    NPU_UDF_VXLAN_DOWN_8,
    NPU_UDF_VXLAN_DOWN_9,
    NPU_UDF_VXLAN_DOWN_10,
    NPU_UDF_VXLAN_DOWN_11,
    NPU_UDF_VXLAN_DOWN_12,
    NPU_UDF_VXLAN_DOWN_13,
    NPU_UDF_VXLAN_DOWN_14,
    NPU_UDF_VXLAN_DOWN_15,
    NPU_UDF_VXLAN_DOWN_16,
    NPU_UDF_VXLAN_DOWN_17,
    NPU_UDF_VXLAN_DOWN_18,
    NPU_UDF_VXLAN_DOWN_19, /*40*/  
    NPU_UDF_MAX_NUM=255
}NPU_UDF_T;

#endif
