##### IGMP configuration #####
igmp-default-version 3
igmp-query-interval 90
igmp-query-response-interval 100
igmp-last-member-query-interval 10
igmp-robustness-value 2
igmp-max-groups 32
igmp-max-sources 32
igmp-max-members 32
igmp-fast-leave 1
igmp-admission-required 0
igmp-admission-bridging-filter 0
igmp-proxy-interfaces 
igmp-snooping-interfaces 
igmp-mcast-interfaces 

##### MLD configuration #####
mld-default-version 2
mld-query-interval 125
mld-query-response-interval 10
mld-last-member-query-interval 10
mld-robustness-value 2
mld-max-groups 32
mld-max-sources 32
mld-max-members 32
mld-fast-leave 1
mld-admission-required 0
mld-admission-bridging-filter 0
mld-proxy-enable 1
mld-snooping-enable 1
mld-proxy-interfaces 
mld-snooping-interfaces 
mld-mcast-interfaces 

##### MCAST configuration #####
igmp-mcast-snoop-exceptions 239.255.255.250/255.255.255.255 224.0.255.135/255.255.255.255
mld-mcast-snoop-exceptions ff05::0001:0003/ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
