#
# Copyright (C) 2009 Samsung Electronics
# Minkyu Kang <mk7.kang@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= hal_io.o
obj-y	+= dramc_pi_basic_api.o
obj-y	+= dramc_pi_calibration_api.o
obj-y	+= dramc_pi_main.o
obj-y	+= dramc.o
