/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ipv6RouterAdvertTable.h"


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ipv6RouterAdvertTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-MIB::ipv6RouterAdvertTable is subid 39 of ip.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.39, length: 8
*/
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     * +-------------+        +==============+
     * |    row    |f|<-------||  object    ||
     * |  create   |1|      E ||  lookup    ||
     * +-------------+        +==============+
     *     E |   | S                 | S
     *       |   +------------------>|
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                               |
     *                          (err && f1)------------------->+
     *                               |                         |
     *                        +--------------+         +--------------+
     *                        |    post      |<--------|      row     |
     *                        |   request    |       U |    release   |
     *                        +--------------+         +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that the undo context has been allocated with
 * ipv6RouterAdvertTable_allocate_data(), but may need extra
 * initialization similar to what you may have done in
 * ipv6RouterAdvertTable_rowreq_ctx_init().
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
ipv6RouterAdvertTable_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_undo_setup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> Setup ipv6RouterAdvertTable undo.
     * set up ipv6RouterAdvertTable undo information, in preparation for a set.
     * Undo storage is in (* ipv6RouterAdvertRowStatus_val_ptr )*
     */

    return rc;
} /* ipv6RouterAdvertTable_undo_setup */

/**
 * Undo a set request.
 *
 * This function will be called before the individual node undo
 * functions are called. If you need to do any undo that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo function will only be called
 * if that node is being set to a new value.
 *
 * If there is anything  specific to a particular column (e.g. releasing
 * memory for a string), you should do that setup in the node's undo
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
ipv6RouterAdvertTable_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_undo","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> ipv6RouterAdvertTable undo.
     * ipv6RouterAdvertTable undo information, in response to a failed set.
     * Undo storage is in (* ipv6RouterAdvertRowStatus_val_ptr )*
     */

    return rc;
} /* ipv6RouterAdvertTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
ipv6RouterAdvertTable_undo_cleanup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_undo_cleanup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:452:M: |-> Cleanup ipv6RouterAdvertTable undo.
     * Undo storage is in (* ipv6RouterAdvertRowStatus_val_ptr )*
     */

    return rc;
} /* ipv6RouterAdvertTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * ipv6RouterAdvertTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param ipv6RouterAdvertTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
ipv6RouterAdvertTable_commit( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    int             save_flags;

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * save flags, then clear until we actually do something
     */
    save_flags = rowreq_ctx->column_set_flags;
    rowreq_ctx->column_set_flags = 0;

    /*
     * commit ipv6RouterAdvertTable data
     * 1) check the column's flag in save_flags to see if it was set.
     * 2) clear the flag when you handle that column
     * 3) set the column's flag in column_set_flags if it needs undo
     *    processing in case of a failure.
     */
    if (save_flags & COLUMN_IPV6ROUTERADVERTSENDADVERTS_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTSENDADVERTS_FLAG; /* clear ipv6RouterAdvertSendAdverts */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertSendAdverts.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertSendAdverts commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertSendAdverts
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTSENDADVERTS_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTMAXINTERVAL_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTMAXINTERVAL_FLAG; /* clear ipv6RouterAdvertMaxInterval */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertMaxInterval.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertMaxInterval commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertMaxInterval
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMAXINTERVAL_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTMININTERVAL_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTMININTERVAL_FLAG; /* clear ipv6RouterAdvertMinInterval */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertMinInterval.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertMinInterval commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertMinInterval
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMININTERVAL_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTMANAGEDFLAG_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTMANAGEDFLAG_FLAG; /* clear ipv6RouterAdvertManagedFlag */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertManagedFlag.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertManagedFlag commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertManagedFlag
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMANAGEDFLAG_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG_FLAG; /* clear ipv6RouterAdvertOtherConfigFlag */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertOtherConfigFlag.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertOtherConfigFlag commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertOtherConfigFlag
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTLINKMTU_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTLINKMTU_FLAG; /* clear ipv6RouterAdvertLinkMTU */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertLinkMTU.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertLinkMTU commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertLinkMTU
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTLINKMTU_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTREACHABLETIME_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTREACHABLETIME_FLAG; /* clear ipv6RouterAdvertReachableTime */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertReachableTime.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertReachableTime commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertReachableTime
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTREACHABLETIME_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTRETRANSMITTIME_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTRETRANSMITTIME_FLAG; /* clear ipv6RouterAdvertRetransmitTime */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertRetransmitTime.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertRetransmitTime commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertRetransmitTime
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTRETRANSMITTIME_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTCURHOPLIMIT_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTCURHOPLIMIT_FLAG; /* clear ipv6RouterAdvertCurHopLimit */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertCurHopLimit.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertCurHopLimit commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertCurHopLimit
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTCURHOPLIMIT_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME_FLAG; /* clear ipv6RouterAdvertDefaultLifetime */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertDefaultLifetime.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertDefaultLifetime commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertDefaultLifetime
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME_FLAG;
       }
    }

    if (save_flags & COLUMN_IPV6ROUTERADVERTROWSTATUS_FLAG) {
       save_flags &= ~COLUMN_IPV6ROUTERADVERTROWSTATUS_FLAG; /* clear ipv6RouterAdvertRowStatus */
       /*
        * TODO:482:o: |-> commit column ipv6RouterAdvertRowStatus.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"ipv6RouterAdvertTable column ipv6RouterAdvertRowStatus commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo ipv6RouterAdvertRowStatus
             */
            rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTROWSTATUS_FLAG;
       }
    }

    /*
     * if we successfully commited this row, set the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags |= MFD_ROW_DIRTY;
    }

    if (save_flags) {
       snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n", save_flags);
       return MFD_ERROR;
    }

    return rc;
} /* ipv6RouterAdvertTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * ipv6RouterAdvertTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param ipv6RouterAdvertTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
ipv6RouterAdvertTable_undo_commit( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_undo_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:485:M: |-> Undo ipv6RouterAdvertTable commit.
     * check the column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & COLUMN__FLAG) {}
     */

    
    /*
     * if we successfully un-commited this row, clear the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return rc;
} /* ipv6RouterAdvertTable_undo_commit */

/*
 * TODO:440:M: Implement ipv6RouterAdvertTable node value checks.
 * TODO:450:M: Implement ipv6RouterAdvertTable undo functions.
 * TODO:460:M: Implement ipv6RouterAdvertTable set functions.
 * TODO:480:M: Implement ipv6RouterAdvertTable commit functions.
 */
/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertSendAdverts
 * ipv6RouterAdvertSendAdverts is subid 2 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.2
 * Description:
A flag indicating whether the router sends periodic
            router advertisements and responds to router solicitations
            on this interface.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: false
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertSendAdverts_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertSendAdverts_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertSendAdverts_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertSendAdverts_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertSendAdverts value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertSendAdverts value not illegal */
} /* ipv6RouterAdvertSendAdverts_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertSendAdverts_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertSendAdverts_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertSendAdverts undo.
     */
    /*
     * copy ipv6RouterAdvertSendAdverts data
     * set rowreq_ctx->undo->ipv6RouterAdvertSendAdverts from rowreq_ctx->data.ipv6RouterAdvertSendAdverts
     */
    rowreq_ctx->undo->ipv6RouterAdvertSendAdverts = rowreq_ctx->data.ipv6RouterAdvertSendAdverts;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertSendAdverts_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertSendAdverts_val
 *        A long containing the new value.
 */
int
ipv6RouterAdvertSendAdverts_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertSendAdverts_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertSendAdverts_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertSendAdverts value.
     * set ipv6RouterAdvertSendAdverts value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertSendAdverts = ipv6RouterAdvertSendAdverts_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertSendAdverts_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertSendAdverts_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertSendAdverts_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertSendAdverts undo.
     */
    /*
     * copy ipv6RouterAdvertSendAdverts data
     * set rowreq_ctx->data.ipv6RouterAdvertSendAdverts from rowreq_ctx->undo->ipv6RouterAdvertSendAdverts
     */
    rowreq_ctx->data.ipv6RouterAdvertSendAdverts = rowreq_ctx->undo->ipv6RouterAdvertSendAdverts;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertSendAdverts_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertMaxInterval
 * ipv6RouterAdvertMaxInterval is subid 3 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.3
 * Description:
The maximum time allowed between sending unsolicited router

            advertisements from this interface.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *   defval: 600
 *
 * Ranges:  4 - 1800;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertMaxInterval_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  4 - 1800
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertMaxInterval_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertMaxInterval_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMaxInterval_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertMaxInterval value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertMaxInterval value not illegal */
} /* ipv6RouterAdvertMaxInterval_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertMaxInterval_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMaxInterval_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertMaxInterval undo.
     */
    /*
     * copy ipv6RouterAdvertMaxInterval data
     * set rowreq_ctx->undo->ipv6RouterAdvertMaxInterval from rowreq_ctx->data.ipv6RouterAdvertMaxInterval
     */
    rowreq_ctx->undo->ipv6RouterAdvertMaxInterval = rowreq_ctx->data.ipv6RouterAdvertMaxInterval;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertMaxInterval_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertMaxInterval_val
 *        A u_long containing the new value.
 */
int
ipv6RouterAdvertMaxInterval_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertMaxInterval_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMaxInterval_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertMaxInterval value.
     * set ipv6RouterAdvertMaxInterval value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertMaxInterval = ipv6RouterAdvertMaxInterval_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertMaxInterval_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertMaxInterval_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMaxInterval_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertMaxInterval undo.
     */
    /*
     * copy ipv6RouterAdvertMaxInterval data
     * set rowreq_ctx->data.ipv6RouterAdvertMaxInterval from rowreq_ctx->undo->ipv6RouterAdvertMaxInterval
     */
    rowreq_ctx->data.ipv6RouterAdvertMaxInterval = rowreq_ctx->undo->ipv6RouterAdvertMaxInterval;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertMaxInterval_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertMinInterval
 * ipv6RouterAdvertMinInterval is subid 4 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.4
 * Description:
The minimum time allowed between sending unsolicited router
            advertisements from this interface.

            The default is 0.33 * ipv6RouterAdvertMaxInterval, however,
            in the case of a low value for ipv6RouterAdvertMaxInterval,
            the minimum value for this object is restricted to 3.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  3 - 1350;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertMinInterval_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  3 - 1350
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertMinInterval_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertMinInterval_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMinInterval_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertMinInterval value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertMinInterval value not illegal */
} /* ipv6RouterAdvertMinInterval_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertMinInterval_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMinInterval_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertMinInterval undo.
     */
    /*
     * copy ipv6RouterAdvertMinInterval data
     * set rowreq_ctx->undo->ipv6RouterAdvertMinInterval from rowreq_ctx->data.ipv6RouterAdvertMinInterval
     */
    rowreq_ctx->undo->ipv6RouterAdvertMinInterval = rowreq_ctx->data.ipv6RouterAdvertMinInterval;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertMinInterval_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertMinInterval_val
 *        A u_long containing the new value.
 */
int
ipv6RouterAdvertMinInterval_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertMinInterval_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMinInterval_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertMinInterval value.
     * set ipv6RouterAdvertMinInterval value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertMinInterval = ipv6RouterAdvertMinInterval_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertMinInterval_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertMinInterval_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMinInterval_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertMinInterval undo.
     */
    /*
     * copy ipv6RouterAdvertMinInterval data
     * set rowreq_ctx->data.ipv6RouterAdvertMinInterval from rowreq_ctx->undo->ipv6RouterAdvertMinInterval
     */
    rowreq_ctx->data.ipv6RouterAdvertMinInterval = rowreq_ctx->undo->ipv6RouterAdvertMinInterval;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertMinInterval_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertManagedFlag
 * ipv6RouterAdvertManagedFlag is subid 5 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.5
 * Description:
The true/false value to be placed into the 'managed address
            configuration' flag field in router advertisements sent from
            this interface.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: false
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertManagedFlag_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertManagedFlag_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertManagedFlag_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertManagedFlag_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertManagedFlag value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertManagedFlag value not illegal */
} /* ipv6RouterAdvertManagedFlag_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertManagedFlag_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertManagedFlag_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertManagedFlag undo.
     */
    /*
     * copy ipv6RouterAdvertManagedFlag data
     * set rowreq_ctx->undo->ipv6RouterAdvertManagedFlag from rowreq_ctx->data.ipv6RouterAdvertManagedFlag
     */
    rowreq_ctx->undo->ipv6RouterAdvertManagedFlag = rowreq_ctx->data.ipv6RouterAdvertManagedFlag;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertManagedFlag_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertManagedFlag_val
 *        A long containing the new value.
 */
int
ipv6RouterAdvertManagedFlag_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertManagedFlag_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertManagedFlag_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertManagedFlag value.
     * set ipv6RouterAdvertManagedFlag value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertManagedFlag = ipv6RouterAdvertManagedFlag_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertManagedFlag_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertManagedFlag_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertManagedFlag_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertManagedFlag undo.
     */
    /*
     * copy ipv6RouterAdvertManagedFlag data
     * set rowreq_ctx->data.ipv6RouterAdvertManagedFlag from rowreq_ctx->undo->ipv6RouterAdvertManagedFlag
     */
    rowreq_ctx->data.ipv6RouterAdvertManagedFlag = rowreq_ctx->undo->ipv6RouterAdvertManagedFlag;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertManagedFlag_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertOtherConfigFlag
 * ipv6RouterAdvertOtherConfigFlag is subid 6 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.6
 * Description:
The true/false value to be placed into the 'other stateful
            configuration' flag field in router advertisements sent from
            this interface.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: false
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertOtherConfigFlag_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertOtherConfigFlag_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertOtherConfigFlag_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertOtherConfigFlag_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertOtherConfigFlag value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertOtherConfigFlag value not illegal */
} /* ipv6RouterAdvertOtherConfigFlag_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertOtherConfigFlag_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertOtherConfigFlag_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertOtherConfigFlag undo.
     */
    /*
     * copy ipv6RouterAdvertOtherConfigFlag data
     * set rowreq_ctx->undo->ipv6RouterAdvertOtherConfigFlag from rowreq_ctx->data.ipv6RouterAdvertOtherConfigFlag
     */
    rowreq_ctx->undo->ipv6RouterAdvertOtherConfigFlag = rowreq_ctx->data.ipv6RouterAdvertOtherConfigFlag;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertOtherConfigFlag_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertOtherConfigFlag_val
 *        A long containing the new value.
 */
int
ipv6RouterAdvertOtherConfigFlag_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertOtherConfigFlag_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertOtherConfigFlag_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertOtherConfigFlag value.
     * set ipv6RouterAdvertOtherConfigFlag value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertOtherConfigFlag = ipv6RouterAdvertOtherConfigFlag_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertOtherConfigFlag_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertOtherConfigFlag_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertOtherConfigFlag_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertOtherConfigFlag undo.
     */
    /*
     * copy ipv6RouterAdvertOtherConfigFlag data
     * set rowreq_ctx->data.ipv6RouterAdvertOtherConfigFlag from rowreq_ctx->undo->ipv6RouterAdvertOtherConfigFlag
     */
    rowreq_ctx->data.ipv6RouterAdvertOtherConfigFlag = rowreq_ctx->undo->ipv6RouterAdvertOtherConfigFlag;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertOtherConfigFlag_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertLinkMTU
 * ipv6RouterAdvertLinkMTU is subid 7 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.7
 * Description:
The value to be placed in MTU options sent by the router on
            this interface.

            A value of zero indicates that no MTU options are sent.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: 0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertLinkMTU_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertLinkMTU_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertLinkMTU_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertLinkMTU_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertLinkMTU value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertLinkMTU value not illegal */
} /* ipv6RouterAdvertLinkMTU_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertLinkMTU_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertLinkMTU_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertLinkMTU undo.
     */
    /*
     * copy ipv6RouterAdvertLinkMTU data
     * set rowreq_ctx->undo->ipv6RouterAdvertLinkMTU from rowreq_ctx->data.ipv6RouterAdvertLinkMTU
     */
    rowreq_ctx->undo->ipv6RouterAdvertLinkMTU = rowreq_ctx->data.ipv6RouterAdvertLinkMTU;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertLinkMTU_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertLinkMTU_val
 *        A u_long containing the new value.
 */
int
ipv6RouterAdvertLinkMTU_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertLinkMTU_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertLinkMTU_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertLinkMTU value.
     * set ipv6RouterAdvertLinkMTU value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertLinkMTU = ipv6RouterAdvertLinkMTU_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertLinkMTU_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertLinkMTU_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertLinkMTU_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertLinkMTU undo.
     */
    /*
     * copy ipv6RouterAdvertLinkMTU data
     * set rowreq_ctx->data.ipv6RouterAdvertLinkMTU from rowreq_ctx->undo->ipv6RouterAdvertLinkMTU
     */
    rowreq_ctx->data.ipv6RouterAdvertLinkMTU = rowreq_ctx->undo->ipv6RouterAdvertLinkMTU;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertLinkMTU_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertReachableTime
 * ipv6RouterAdvertReachableTime is subid 8 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.8
 * Description:
The value to be placed in the reachable time field in router
            advertisement messages sent from this interface.

            A value of zero in the router advertisement indicates that
            the advertisement isn't specifying a value for reachable
            time.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *   defval: 0
 *
 * Ranges:  0 - 3600000;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertReachableTime_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  0 - 3600000
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertReachableTime_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertReachableTime_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertReachableTime_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertReachableTime value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertReachableTime value not illegal */
} /* ipv6RouterAdvertReachableTime_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertReachableTime_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertReachableTime_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertReachableTime undo.
     */
    /*
     * copy ipv6RouterAdvertReachableTime data
     * set rowreq_ctx->undo->ipv6RouterAdvertReachableTime from rowreq_ctx->data.ipv6RouterAdvertReachableTime
     */
    rowreq_ctx->undo->ipv6RouterAdvertReachableTime = rowreq_ctx->data.ipv6RouterAdvertReachableTime;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertReachableTime_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertReachableTime_val
 *        A u_long containing the new value.
 */
int
ipv6RouterAdvertReachableTime_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertReachableTime_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertReachableTime_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertReachableTime value.
     * set ipv6RouterAdvertReachableTime value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertReachableTime = ipv6RouterAdvertReachableTime_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertReachableTime_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertReachableTime_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertReachableTime_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertReachableTime undo.
     */
    /*
     * copy ipv6RouterAdvertReachableTime data
     * set rowreq_ctx->data.ipv6RouterAdvertReachableTime from rowreq_ctx->undo->ipv6RouterAdvertReachableTime
     */
    rowreq_ctx->data.ipv6RouterAdvertReachableTime = rowreq_ctx->undo->ipv6RouterAdvertReachableTime;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertReachableTime_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertRetransmitTime
 * ipv6RouterAdvertRetransmitTime is subid 9 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.9
 * Description:
The value to be placed in the retransmit timer field in
            router advertisements sent from this interface.

            A value of zero in the router advertisement indicates that
            the advertisement isn't specifying a value for retrans
            time.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: 0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertRetransmitTime_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertRetransmitTime_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertRetransmitTime_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRetransmitTime_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertRetransmitTime value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertRetransmitTime value not illegal */
} /* ipv6RouterAdvertRetransmitTime_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertRetransmitTime_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRetransmitTime_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertRetransmitTime undo.
     */
    /*
     * copy ipv6RouterAdvertRetransmitTime data
     * set rowreq_ctx->undo->ipv6RouterAdvertRetransmitTime from rowreq_ctx->data.ipv6RouterAdvertRetransmitTime
     */
    rowreq_ctx->undo->ipv6RouterAdvertRetransmitTime = rowreq_ctx->data.ipv6RouterAdvertRetransmitTime;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertRetransmitTime_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertRetransmitTime_val
 *        A u_long containing the new value.
 */
int
ipv6RouterAdvertRetransmitTime_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertRetransmitTime_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRetransmitTime_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertRetransmitTime value.
     * set ipv6RouterAdvertRetransmitTime value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertRetransmitTime = ipv6RouterAdvertRetransmitTime_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertRetransmitTime_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertRetransmitTime_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRetransmitTime_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertRetransmitTime undo.
     */
    /*
     * copy ipv6RouterAdvertRetransmitTime data
     * set rowreq_ctx->data.ipv6RouterAdvertRetransmitTime from rowreq_ctx->undo->ipv6RouterAdvertRetransmitTime
     */
    rowreq_ctx->data.ipv6RouterAdvertRetransmitTime = rowreq_ctx->undo->ipv6RouterAdvertRetransmitTime;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertRetransmitTime_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertCurHopLimit
 * ipv6RouterAdvertCurHopLimit is subid 10 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.10
 * Description:
The default value to be placed in the current hop limit
            field in router advertisements sent from this interface.

            The value should be set to the current diameter of the
            Internet.

            A value of zero in the router advertisement indicates that
            the advertisement isn't specifying a value for curHopLimit.

            The default should be set to the value specified in the IANA
            web pages (www.iana.org) at the time of implementation.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertCurHopLimit_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  0 - 255
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertCurHopLimit_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertCurHopLimit_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertCurHopLimit_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertCurHopLimit value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertCurHopLimit value not illegal */
} /* ipv6RouterAdvertCurHopLimit_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertCurHopLimit_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertCurHopLimit_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertCurHopLimit undo.
     */
    /*
     * copy ipv6RouterAdvertCurHopLimit data
     * set rowreq_ctx->undo->ipv6RouterAdvertCurHopLimit from rowreq_ctx->data.ipv6RouterAdvertCurHopLimit
     */
    rowreq_ctx->undo->ipv6RouterAdvertCurHopLimit = rowreq_ctx->data.ipv6RouterAdvertCurHopLimit;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertCurHopLimit_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertCurHopLimit_val
 *        A u_long containing the new value.
 */
int
ipv6RouterAdvertCurHopLimit_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertCurHopLimit_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertCurHopLimit_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertCurHopLimit value.
     * set ipv6RouterAdvertCurHopLimit value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertCurHopLimit = ipv6RouterAdvertCurHopLimit_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertCurHopLimit_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertCurHopLimit_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertCurHopLimit_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertCurHopLimit undo.
     */
    /*
     * copy ipv6RouterAdvertCurHopLimit data
     * set rowreq_ctx->data.ipv6RouterAdvertCurHopLimit from rowreq_ctx->undo->ipv6RouterAdvertCurHopLimit
     */
    rowreq_ctx->data.ipv6RouterAdvertCurHopLimit = rowreq_ctx->undo->ipv6RouterAdvertCurHopLimit;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertCurHopLimit_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertDefaultLifetime
 * ipv6RouterAdvertDefaultLifetime is subid 11 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.11
 * Description:
The value to be placed in the router lifetime field of
            router advertisements sent from this interface.  This value
            MUST be either 0 or between ipv6RouterAdvertMaxInterval and
            9000 seconds.

            A value of zero indicates that the router is not to be used
            as a default router.

            The default is 3 * ipv6RouterAdvertMaxInterval.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0, 4 - 9000;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertDefaultLifetime_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  0, 4 - 9000
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertDefaultLifetime_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertDefaultLifetime_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertDefaultLifetime_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertDefaultLifetime value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertDefaultLifetime value not illegal */
} /* ipv6RouterAdvertDefaultLifetime_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertDefaultLifetime_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertDefaultLifetime_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertDefaultLifetime undo.
     */
    /*
     * copy ipv6RouterAdvertDefaultLifetime data
     * set rowreq_ctx->undo->ipv6RouterAdvertDefaultLifetime from rowreq_ctx->data.ipv6RouterAdvertDefaultLifetime
     */
    rowreq_ctx->undo->ipv6RouterAdvertDefaultLifetime = rowreq_ctx->data.ipv6RouterAdvertDefaultLifetime;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertDefaultLifetime_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertDefaultLifetime_val
 *        A u_long containing the new value.
 */
int
ipv6RouterAdvertDefaultLifetime_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertDefaultLifetime_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertDefaultLifetime_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertDefaultLifetime value.
     * set ipv6RouterAdvertDefaultLifetime value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertDefaultLifetime = ipv6RouterAdvertDefaultLifetime_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertDefaultLifetime_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertDefaultLifetime_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertDefaultLifetime_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertDefaultLifetime undo.
     */
    /*
     * copy ipv6RouterAdvertDefaultLifetime data
     * set rowreq_ctx->data.ipv6RouterAdvertDefaultLifetime from rowreq_ctx->undo->ipv6RouterAdvertDefaultLifetime
     */
    rowreq_ctx->data.ipv6RouterAdvertDefaultLifetime = rowreq_ctx->undo->ipv6RouterAdvertDefaultLifetime;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertDefaultLifetime_undo */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertRowStatus
 * ipv6RouterAdvertRowStatus is subid 12 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.12
 * Description:
The status of this conceptual row.

            As all objects in this conceptual row have default values, a
            row can be created and made active by setting this object
            appropriately.

            The RowStatus TC requires that this DESCRIPTION clause
            states under which circumstances other objects in this row
            can be modified.  The value of this object has no effect on
            whether other objects in this conceptual row can be
            modified.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 4/8. Values:  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * Its syntax is RowStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertRowStatus_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * ipv6RouterAdvertTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
ipv6RouterAdvertRowStatus_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertRowStatus_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRowStatus_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid ipv6RouterAdvertRowStatus value.
     */

    return MFD_SUCCESS; /* ipv6RouterAdvertRowStatus value not illegal */
} /* ipv6RouterAdvertRowStatus_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (ipv6RouterAdvertTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * ipv6RouterAdvertTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
ipv6RouterAdvertRowStatus_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRowStatus_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup ipv6RouterAdvertRowStatus undo.
     */
    /*
     * copy ipv6RouterAdvertRowStatus data
     * set rowreq_ctx->undo->ipv6RouterAdvertRowStatus from rowreq_ctx->data.ipv6RouterAdvertRowStatus
     */
    rowreq_ctx->undo->ipv6RouterAdvertRowStatus = rowreq_ctx->data.ipv6RouterAdvertRowStatus;


    return MFD_SUCCESS;
} /* ipv6RouterAdvertRowStatus_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param ipv6RouterAdvertRowStatus_val
 *        A long containing the new value.
 */
int
ipv6RouterAdvertRowStatus_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertRowStatus_val )
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRowStatus_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set ipv6RouterAdvertRowStatus value.
     * set ipv6RouterAdvertRowStatus value in rowreq_ctx->data
     */
    rowreq_ctx->data.ipv6RouterAdvertRowStatus = ipv6RouterAdvertRowStatus_val;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertRowStatus_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
ipv6RouterAdvertRowStatus_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRowStatus_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up ipv6RouterAdvertRowStatus undo.
     */
    /*
     * copy ipv6RouterAdvertRowStatus data
     * set rowreq_ctx->data.ipv6RouterAdvertRowStatus from rowreq_ctx->undo->ipv6RouterAdvertRowStatus
     */
    rowreq_ctx->data.ipv6RouterAdvertRowStatus = rowreq_ctx->undo->ipv6RouterAdvertRowStatus;

    
    return MFD_SUCCESS;
} /* ipv6RouterAdvertRowStatus_undo */

/** @} */
