/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ipv6RouterAdvertTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement ipv6RouterAdvertTable get routines.
 * TODO:240:M: Implement ipv6RouterAdvertTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ipv6RouterAdvertTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-MIB::ipv6RouterAdvertTable is subid 39 of ip.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.39, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement ipv6RouterAdvertTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param ipv6RouterAdvertIfIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
ipv6RouterAdvertTable_indexes_set_tbl_idx(ipv6RouterAdvertTable_mib_index *tbl_idx, long ipv6RouterAdvertIfIndex_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_indexes_set_tbl_idx","called\n"));

    /* ipv6RouterAdvertIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H */
    tbl_idx->ipv6RouterAdvertIfIndex = ipv6RouterAdvertIfIndex_val;
    

    return MFD_SUCCESS;
} /* ipv6RouterAdvertTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
ipv6RouterAdvertTable_indexes_set(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, long ipv6RouterAdvertIfIndex_val)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_indexes_set","called\n"));

    if(MFD_SUCCESS != ipv6RouterAdvertTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , ipv6RouterAdvertIfIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != ipv6RouterAdvertTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* ipv6RouterAdvertTable_indexes_set */


/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertSendAdverts
 * ipv6RouterAdvertSendAdverts is subid 2 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.2
 * Description:
A flag indicating whether the router sends periodic
            router advertisements and responds to router solicitations
            on this interface.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: false
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertSendAdverts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertSendAdverts_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertSendAdverts_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertSendAdverts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertSendAdverts_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertSendAdverts_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertSendAdverts data.
 * copy (* ipv6RouterAdvertSendAdverts_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertSendAdverts_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertSendAdverts;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertSendAdverts_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertMaxInterval
 * ipv6RouterAdvertMaxInterval is subid 3 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.3
 * Description:
The maximum time allowed between sending unsolicited router

            advertisements from this interface.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *   defval: 600
 *
 * Ranges:  4 - 1800;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertMaxInterval data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertMaxInterval_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertMaxInterval_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertMaxInterval_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertMaxInterval_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMaxInterval_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertMaxInterval data.
 * copy (* ipv6RouterAdvertMaxInterval_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertMaxInterval_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertMaxInterval;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertMaxInterval_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertMinInterval
 * ipv6RouterAdvertMinInterval is subid 4 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.4
 * Description:
The minimum time allowed between sending unsolicited router
            advertisements from this interface.

            The default is 0.33 * ipv6RouterAdvertMaxInterval, however,
            in the case of a low value for ipv6RouterAdvertMaxInterval,
            the minimum value for this object is restricted to 3.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  3 - 1350;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertMinInterval data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertMinInterval_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertMinInterval_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertMinInterval_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertMinInterval_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertMinInterval_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertMinInterval data.
 * copy (* ipv6RouterAdvertMinInterval_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertMinInterval_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertMinInterval;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertMinInterval_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertManagedFlag
 * ipv6RouterAdvertManagedFlag is subid 5 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.5
 * Description:
The true/false value to be placed into the 'managed address
            configuration' flag field in router advertisements sent from
            this interface.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: false
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertManagedFlag data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertManagedFlag_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertManagedFlag_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertManagedFlag_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertManagedFlag_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertManagedFlag_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertManagedFlag data.
 * copy (* ipv6RouterAdvertManagedFlag_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertManagedFlag_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertManagedFlag;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertManagedFlag_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertOtherConfigFlag
 * ipv6RouterAdvertOtherConfigFlag is subid 6 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.6
 * Description:
The true/false value to be placed into the 'other stateful
            configuration' flag field in router advertisements sent from
            this interface.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: false
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertOtherConfigFlag data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertOtherConfigFlag_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertOtherConfigFlag_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertOtherConfigFlag_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertOtherConfigFlag_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertOtherConfigFlag_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertOtherConfigFlag data.
 * copy (* ipv6RouterAdvertOtherConfigFlag_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertOtherConfigFlag_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertOtherConfigFlag;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertOtherConfigFlag_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertLinkMTU
 * ipv6RouterAdvertLinkMTU is subid 7 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.7
 * Description:
The value to be placed in MTU options sent by the router on
            this interface.

            A value of zero indicates that no MTU options are sent.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: 0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertLinkMTU data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertLinkMTU_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertLinkMTU_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertLinkMTU_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertLinkMTU_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertLinkMTU_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertLinkMTU data.
 * copy (* ipv6RouterAdvertLinkMTU_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertLinkMTU_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertLinkMTU;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertLinkMTU_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertReachableTime
 * ipv6RouterAdvertReachableTime is subid 8 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.8
 * Description:
The value to be placed in the reachable time field in router
            advertisement messages sent from this interface.

            A value of zero in the router advertisement indicates that
            the advertisement isn't specifying a value for reachable
            time.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *   defval: 0
 *
 * Ranges:  0 - 3600000;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertReachableTime data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertReachableTime_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertReachableTime_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertReachableTime_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertReachableTime_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertReachableTime_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertReachableTime data.
 * copy (* ipv6RouterAdvertReachableTime_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertReachableTime_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertReachableTime;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertReachableTime_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertRetransmitTime
 * ipv6RouterAdvertRetransmitTime is subid 9 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.9
 * Description:
The value to be placed in the retransmit timer field in
            router advertisements sent from this interface.

            A value of zero in the router advertisement indicates that
            the advertisement isn't specifying a value for retrans
            time.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *   defval: 0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertRetransmitTime data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertRetransmitTime_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertRetransmitTime_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertRetransmitTime_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertRetransmitTime_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertRetransmitTime_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertRetransmitTime data.
 * copy (* ipv6RouterAdvertRetransmitTime_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertRetransmitTime_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertRetransmitTime;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertRetransmitTime_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertCurHopLimit
 * ipv6RouterAdvertCurHopLimit is subid 10 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.10
 * Description:
The default value to be placed in the current hop limit
            field in router advertisements sent from this interface.

            The value should be set to the current diameter of the
            Internet.

            A value of zero in the router advertisement indicates that
            the advertisement isn't specifying a value for curHopLimit.

            The default should be set to the value specified in the IANA
            web pages (www.iana.org) at the time of implementation.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertCurHopLimit data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertCurHopLimit_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertCurHopLimit_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertCurHopLimit_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertCurHopLimit_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertCurHopLimit_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertCurHopLimit data.
 * copy (* ipv6RouterAdvertCurHopLimit_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertCurHopLimit_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertCurHopLimit;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertCurHopLimit_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertDefaultLifetime
 * ipv6RouterAdvertDefaultLifetime is subid 11 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.11
 * Description:
The value to be placed in the router lifetime field of
            router advertisements sent from this interface.  This value
            MUST be either 0 or between ipv6RouterAdvertMaxInterval and
            9000 seconds.

            A value of zero indicates that the router is not to be used
            as a default router.

            The default is 3 * ipv6RouterAdvertMaxInterval.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0, 4 - 9000;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertDefaultLifetime data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertDefaultLifetime_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertDefaultLifetime_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertDefaultLifetime_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertDefaultLifetime_val_ptr );


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertDefaultLifetime_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ipv6RouterAdvertDefaultLifetime data.
 * copy (* ipv6RouterAdvertDefaultLifetime_val_ptr ) from rowreq_ctx->data
 */
    (* ipv6RouterAdvertDefaultLifetime_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertDefaultLifetime;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertDefaultLifetime_get */

/*---------------------------------------------------------------------
 * IP-MIB::ipv6RouterAdvertEntry.ipv6RouterAdvertRowStatus
 * ipv6RouterAdvertRowStatus is subid 12 of ipv6RouterAdvertEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.2.1.4.39.1.12
 * Description:
The status of this conceptual row.

            As all objects in this conceptual row have default values, a
            row can be created and made active by setting this object
            appropriately.

            The RowStatus TC requires that this DESCRIPTION clause
            states under which circumstances other objects in this row
            can be modified.  The value of this object has no effect on
            whether other objects in this conceptual row can be
            modified.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 4/8. Values:  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * Its syntax is RowStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the ipv6RouterAdvertRowStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ipv6RouterAdvertRowStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ipv6RouterAdvertRowStatus_get( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long * ipv6RouterAdvertRowStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ipv6RouterAdvertRowStatus_val_ptr );

    (* ipv6RouterAdvertRowStatus_val_ptr ) = rowreq_ctx->data.ipv6RouterAdvertRowStatus;

    return MFD_SUCCESS;
} /* ipv6RouterAdvertRowStatus_get */



/** @} */
