/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ipv6RouterAdvertTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "ipv6RouterAdvertTable_interface.h"

netsnmp_feature_require(baby_steps)
netsnmp_feature_require(row_merge)
netsnmp_feature_require(check_all_requests_error)

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table ipv6RouterAdvertTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-MIB::ipv6RouterAdvertTable is subid 39 of ip.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.39, length: 8
*/
typedef struct ipv6RouterAdvertTable_interface_ctx_s {

   netsnmp_container              *container;

   ipv6RouterAdvertTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

    u_int                             table_dirty;

} ipv6RouterAdvertTable_interface_ctx;

static ipv6RouterAdvertTable_interface_ctx ipv6RouterAdvertTable_if_ctx;

static void _ipv6RouterAdvertTable_container_init(
    ipv6RouterAdvertTable_interface_ctx *if_ctx);
static void _ipv6RouterAdvertTable_container_shutdown(
    ipv6RouterAdvertTable_interface_ctx *if_ctx);


netsnmp_container *
ipv6RouterAdvertTable_container_get( void )
{
    return ipv6RouterAdvertTable_if_ctx.container;
}

ipv6RouterAdvertTable_registration *
ipv6RouterAdvertTable_registration_get( void )
{
    return ipv6RouterAdvertTable_if_ctx.user_ctx;
}

ipv6RouterAdvertTable_registration *
ipv6RouterAdvertTable_registration_set( ipv6RouterAdvertTable_registration * newreg )
{
    ipv6RouterAdvertTable_registration * old = ipv6RouterAdvertTable_if_ctx.user_ctx;
    ipv6RouterAdvertTable_if_ctx.user_ctx = newreg;
    return old;
}

int
ipv6RouterAdvertTable_container_size( void )
{
    return CONTAINER_SIZE(ipv6RouterAdvertTable_if_ctx.container);
}

u_int
ipv6RouterAdvertTable_dirty_get( void )
{
    return ipv6RouterAdvertTable_if_ctx.table_dirty;
}

void
ipv6RouterAdvertTable_dirty_set( u_int status )
{
    DEBUGMSGTL(("ipv6RouterAdvertTable:ipv6RouterAdvertTable_dirty_set",
                "called. was %d, now %d\n",
                ipv6RouterAdvertTable_if_ctx.table_dirty, status));
    ipv6RouterAdvertTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_pre_request;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_post_request;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_object_lookup;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_get_values;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_check_objects;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_undo_setup;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_set_values;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_undo_cleanup;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_undo_values;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_commit;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_undo_commit;
static Netsnmp_Node_Handler _mfd_ipv6RouterAdvertTable_irreversible_commit;

ipv6RouterAdvertTable_data *ipv6RouterAdvertTable_allocate_data(void);

/**
 * @internal
 * Initialize the table ipv6RouterAdvertTable 
 *    (Define its contents and how it's structured)
 */
void
_ipv6RouterAdvertTable_initialize_interface(ipv6RouterAdvertTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &ipv6RouterAdvertTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &ipv6RouterAdvertTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_ipv6RouterAdvertTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for ipv6RouterAdvertTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: ipv6RouterAdvertIfIndex */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrieval. */
    tbl_info->min_column = IPV6ROUTERADVERTTABLE_MIN_COL;
    tbl_info->max_column = IPV6ROUTERADVERTTABLE_MAX_COL;

    /*
     * save users context
     */
    ipv6RouterAdvertTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    ipv6RouterAdvertTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _ipv6RouterAdvertTable_container_init(&ipv6RouterAdvertTable_if_ctx);
    if (NULL == ipv6RouterAdvertTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for ipv6RouterAdvertTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_ipv6RouterAdvertTable_object_lookup;
    access_multiplexer->get_values = _mfd_ipv6RouterAdvertTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_ipv6RouterAdvertTable_pre_request;
    access_multiplexer->post_request = _mfd_ipv6RouterAdvertTable_post_request;

#ifndef NETSNMP_DISABLE_SET_SUPPORT

    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks = _mfd_ipv6RouterAdvertTable_check_objects;
    access_multiplexer->undo_setup = _mfd_ipv6RouterAdvertTable_undo_setup;
    access_multiplexer->undo_cleanup = _mfd_ipv6RouterAdvertTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_ipv6RouterAdvertTable_set_values;
    access_multiplexer->undo_sets = _mfd_ipv6RouterAdvertTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_ipv6RouterAdvertTable_commit;
    access_multiplexer->undo_commit = _mfd_ipv6RouterAdvertTable_undo_commit;
    access_multiplexer->irreversible_commit = _mfd_ipv6RouterAdvertTable_irreversible_commit;
#endif

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("ipv6RouterAdvertTable:init_ipv6RouterAdvertTable",
                "Registering ipv6RouterAdvertTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("ipv6RouterAdvertTable", handler,
                                                  ipv6RouterAdvertTable_oid,
                                                  ipv6RouterAdvertTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
                                                  HANDLER_CAN_RONLY
#else
                                                  HANDLER_CAN_RWRITE
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table ipv6RouterAdvertTable\n");
        return;
    }
    reginfo->my_reg_void = &ipv6RouterAdvertTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            ipv6RouterAdvertTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _ipv6RouterAdvertTable_initialize_interface */

/**
 * @internal
 * Shutdown the table ipv6RouterAdvertTable
 */
void
_ipv6RouterAdvertTable_shutdown_interface(ipv6RouterAdvertTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _ipv6RouterAdvertTable_container_shutdown(&ipv6RouterAdvertTable_if_ctx);
}

void
ipv6RouterAdvertTable_valid_columns_set(netsnmp_column_info *vc)
{
    ipv6RouterAdvertTable_if_ctx.tbl_info.valid_columns = vc;
} /* ipv6RouterAdvertTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
ipv6RouterAdvertTable_index_to_oid(netsnmp_index *oid_idx,
                         ipv6RouterAdvertTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * ipv6RouterAdvertIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H
     */
    netsnmp_variable_list var_ipv6RouterAdvertIfIndex;

    /*
     * set up varbinds
     */
    memset( &var_ipv6RouterAdvertIfIndex, 0x00, sizeof(var_ipv6RouterAdvertIfIndex) );
    var_ipv6RouterAdvertIfIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_ipv6RouterAdvertIfIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_index_to_oid","called\n"));

        /* ipv6RouterAdvertIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H */
    snmp_set_var_value(&var_ipv6RouterAdvertIfIndex, &mib_idx->ipv6RouterAdvertIfIndex, sizeof(mib_idx->ipv6RouterAdvertIfIndex));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_ipv6RouterAdvertIfIndex);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_ipv6RouterAdvertIfIndex );

    return err;
} /* ipv6RouterAdvertTable_index_to_oid */

/**
 * extract ipv6RouterAdvertTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
ipv6RouterAdvertTable_index_from_oid(netsnmp_index *oid_idx,
                         ipv6RouterAdvertTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * ipv6RouterAdvertIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H
     */
    netsnmp_variable_list var_ipv6RouterAdvertIfIndex;

    /*
     * set up varbinds
     */
    memset( &var_ipv6RouterAdvertIfIndex, 0x00, sizeof(var_ipv6RouterAdvertIfIndex) );
    var_ipv6RouterAdvertIfIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_ipv6RouterAdvertIfIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_ipv6RouterAdvertIfIndex );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->ipv6RouterAdvertIfIndex = *((long *)var_ipv6RouterAdvertIfIndex.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_ipv6RouterAdvertIfIndex );

    return err;
} /* ipv6RouterAdvertTable_index_from_oid */


/*
 * ipv6RouterAdvertTable_allocate_data
 *
 * Purpose: create new ipv6RouterAdvertTable_data.
 */
ipv6RouterAdvertTable_data *
ipv6RouterAdvertTable_allocate_data(void)
{
    ipv6RouterAdvertTable_data *rtn = SNMP_MALLOC_TYPEDEF(ipv6RouterAdvertTable_data);

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_allocate_data","called\n"));

    if(NULL == rtn) {
        snmp_log(LOG_ERR, "unable to malloc memory for new "
                 "ipv6RouterAdvertTable_data.\n");
    }

    return rtn;
} /* ipv6RouterAdvertTable_allocate_data */

/*
 * ipv6RouterAdvertTable_release_data
 *
 * Purpose: release ipv6RouterAdvertTable data.
 */
void
ipv6RouterAdvertTable_release_data(ipv6RouterAdvertTable_data *data)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_release_data","called\n"));

    free(data);
} /* ipv6RouterAdvertTable_release_data */

/* *********************************************************************
 * @internal
 * allocate resources for a ipv6RouterAdvertTable_rowreq_ctx
 */
ipv6RouterAdvertTable_rowreq_ctx *
ipv6RouterAdvertTable_allocate_rowreq_ctx(void *user_init_ctx)
{
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(ipv6RouterAdvertTable_rowreq_ctx);

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:ipv6RouterAdvertTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "ipv6RouterAdvertTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->ipv6RouterAdvertTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
        if(SNMPERR_SUCCESS !=
            ipv6RouterAdvertTable_rowreq_ctx_init(rowreq_ctx, user_init_ctx)) {
           ipv6RouterAdvertTable_release_rowreq_ctx(rowreq_ctx);
           rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* ipv6RouterAdvertTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a ipv6RouterAdvertTable_rowreq_ctx
 */
void
ipv6RouterAdvertTable_release_rowreq_ctx(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:ipv6RouterAdvertTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    ipv6RouterAdvertTable_rowreq_ctx_cleanup(rowreq_ctx);

    if(rowreq_ctx->undo)
        ipv6RouterAdvertTable_release_data(rowreq_ctx->undo);
 
    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* ipv6RouterAdvertTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_ipv6RouterAdvertTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:ipv6RouterAdvertTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = ipv6RouterAdvertTable_pre_request(ipv6RouterAdvertTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("ipv6RouterAdvertTable","error %d from "
                    "ipv6RouterAdvertTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_ipv6RouterAdvertTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        ipv6RouterAdvertTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:ipv6RouterAdvertTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    if ((MFD_SUCCESS != packet_rc) && ipv6RouterAdvertTable_dirty_get()) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        snmp_log(LOG_WARNING, "ipv6RouterAdvertTable dirty flag set in post_request "
                 "but status != SUCCESS.\n");
    }

    rc = ipv6RouterAdvertTable_post_request(ipv6RouterAdvertTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("ipv6RouterAdvertTable","error %d from "
                    "ipv6RouterAdvertTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_post_request */

NETSNMP_STATIC_INLINE int
_ipv6RouterAdvertTable_check_indexes(ipv6RouterAdvertTable_rowreq_ctx * rowreq_ctx)
{
    int                          rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_indexes","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);


    /* (INDEX) ipv6RouterAdvertIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H */
    /* check defined range(s). */
    if( (SNMPERR_SUCCESS == rc)
       && ((rowreq_ctx->tbl_idx.ipv6RouterAdvertIfIndex < 1) || (rowreq_ctx->tbl_idx.ipv6RouterAdvertIfIndex > 2147483647))
     ) {
        rc = SNMP_ERR_WRONGVALUE;
    }
       if (MFD_SUCCESS != rc)
          return rc;
        rc = ipv6RouterAdvertIfIndex_check_index( rowreq_ctx );
       if(MFD_SUCCESS != rc)
           return SNMP_ERR_NOCREATION;

    /*
     * if individual parts look ok, check them as a whole
     */
    return ipv6RouterAdvertTable_validate_index( ipv6RouterAdvertTable_if_ctx.user_ctx, rowreq_ctx );
} /* _ipv6RouterAdvertTable_check_indexes */
/**
 * @internal
 * wrapper
 */
static ipv6RouterAdvertTable_rowreq_ctx *
_mfd_ipv6RouterAdvertTable_rowreq_from_index(netsnmp_index *oid_idx, int * rc_ptr)
{
    ipv6RouterAdvertTable_rowreq_ctx * rowreq_ctx;
    ipv6RouterAdvertTable_mib_index mib_idx;
    int rc;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_rowreq_from_index",
                "called\n"));

    if (NULL == rc_ptr)
        rc_ptr = &rc;
    *rc_ptr = MFD_SUCCESS;

    memset(&mib_idx, 0x0, sizeof(mib_idx));
    
    /*
     * try to parse oid
     */
    *rc_ptr = ipv6RouterAdvertTable_index_from_oid(oid_idx, &mib_idx);
    if(MFD_SUCCESS != *rc_ptr) {
        DEBUGMSGT(("ipv6RouterAdvertTable", "error parsing index\n"));
        return NULL;
    }

    /*
     * allocate new context
     */
    rowreq_ctx = ipv6RouterAdvertTable_allocate_rowreq_ctx(NULL);
    if (NULL == rowreq_ctx) {
        *rc_ptr = MFD_ERROR;
        return NULL; /* msg already logged */
    }
    
    memcpy(&rowreq_ctx->tbl_idx, &mib_idx, sizeof(mib_idx));

    /*
     * check indexes
     */
    *rc_ptr = _ipv6RouterAdvertTable_check_indexes(rowreq_ctx);
    if(MFD_SUCCESS != *rc_ptr) {
        netsnmp_assert((*rc_ptr == SNMP_ERR_NOCREATION) ||
                       (*rc_ptr == SNMP_ERR_INCONSISTENTNAME));
        ipv6RouterAdvertTable_release_rowreq_ctx(rowreq_ctx);
        return NULL;
    }

    /*
     * copy indexes
     */
    rowreq_ctx->oid_idx.len = oid_idx->len;
    memcpy(rowreq_ctx->oid_idx.oids, oid_idx->oids, oid_idx->len * sizeof(oid));

    return rowreq_ctx;
} /* _mfd_ipv6RouterAdvertTable_rowreq_from_index */


/**
 * @internal
 * wrapper
 */
static int
_mfd_ipv6RouterAdvertTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * ipv6RouterAdvertTable_interface_ctx *if_ctx =
     *             (ipv6RouterAdvertTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        netsnmp_table_request_info *tblreq_info;
        netsnmp_index oid_idx;

        tblreq_info = netsnmp_extract_table_info(requests);
        if(NULL == tblreq_info) {
            snmp_log(LOG_ERR, "request had no table info\n");
            return MFD_ERROR;
        }

        /*
         * try create rowreq
         */
        oid_idx.oids = tblreq_info->index_oid;
        oid_idx.len = tblreq_info->index_oid_len;

        rowreq_ctx = _mfd_ipv6RouterAdvertTable_rowreq_from_index(&oid_idx, &rc);
        if(MFD_SUCCESS == rc) {
            netsnmp_assert(NULL != rowreq_ctx);
            rowreq_ctx->rowreq_flags |= MFD_ROW_CREATED;
            /*
             * add rowreq_ctx to request data lists
             */
            netsnmp_container_table_row_insert(requests, (netsnmp_index*)rowreq_ctx);
        }
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        ipv6RouterAdvertTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_ipv6RouterAdvertTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_ipv6RouterAdvertTable_get_column( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* ipv6RouterAdvertSendAdverts(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTSENDADVERTS:
		var->val_len = sizeof(u_long);
		var->type = ASN_INTEGER;
		rc = ipv6RouterAdvertSendAdverts_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertMaxInterval(3)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTMAXINTERVAL:
		var->val_len = sizeof(u_long);
		var->type = ASN_UNSIGNED;
		rc = ipv6RouterAdvertMaxInterval_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertMinInterval(4)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTMININTERVAL:
		var->val_len = sizeof(u_long);
		var->type = ASN_UNSIGNED;
		rc = ipv6RouterAdvertMinInterval_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertManagedFlag(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTMANAGEDFLAG:
		var->val_len = sizeof(u_long);
		var->type = ASN_INTEGER;
		rc = ipv6RouterAdvertManagedFlag_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertOtherConfigFlag(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG:
		var->val_len = sizeof(u_long);
		var->type = ASN_INTEGER;
		rc = ipv6RouterAdvertOtherConfigFlag_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertLinkMTU(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTLINKMTU:
		var->val_len = sizeof(u_long);
		var->type = ASN_UNSIGNED;
		rc = ipv6RouterAdvertLinkMTU_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertReachableTime(8)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTREACHABLETIME:
		var->val_len = sizeof(u_long);
		var->type = ASN_UNSIGNED;
		rc = ipv6RouterAdvertReachableTime_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertRetransmitTime(9)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTRETRANSMITTIME:
		var->val_len = sizeof(u_long);
		var->type = ASN_UNSIGNED;
		rc = ipv6RouterAdvertRetransmitTime_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertCurHopLimit(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTCURHOPLIMIT:
		var->val_len = sizeof(u_long);
		var->type = ASN_UNSIGNED;
		rc = ipv6RouterAdvertCurHopLimit_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertDefaultLifetime(11)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME:
		var->val_len = sizeof(u_long);
		var->type = ASN_UNSIGNED;
		rc = ipv6RouterAdvertDefaultLifetime_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* ipv6RouterAdvertRowStatus(12)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_IPV6ROUTERADVERTROWSTATUS:
		var->val_len = sizeof(u_long);
		var->type = ASN_INTEGER;
		rc = ipv6RouterAdvertRowStatus_get(rowreq_ctx, (u_long *)var->val.string );
        break;

     default:
        if (IPV6ROUTERADVERTTABLE_MIN_COL <= column && column <= IPV6ROUTERADVERTTABLE_MAX_COL) {
            DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _ipv6RouterAdvertTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _ipv6RouterAdvertTable_get_column */

int
_mfd_ipv6RouterAdvertTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _ipv6RouterAdvertTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
NETSNMP_STATIC_INLINE int
_ipv6RouterAdvertTable_check_column( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx,
                         netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {
    /* (INDEX) ipv6RouterAdvertIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H */
    case COLUMN_IPV6ROUTERADVERTIFINDEX:
        rc = SNMP_ERR_NOTWRITABLE; /* can not change index of active row */
        break;

    /* ipv6RouterAdvertSendAdverts(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTSENDADVERTS:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertSendAdverts ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != TRUTHVALUE_TRUE )
 && ( *var->val.integer != TRUTHVALUE_FALSE )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertSendAdverts",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertSendAdverts_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertSendAdverts_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertMaxInterval(3)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTMAXINTERVAL:
    rc = netsnmp_check_vb_type_and_size( var, ASN_UNSIGNED,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertMaxInterval ) );
    /* check defined range(s). */
    if( (SNMPERR_SUCCESS == rc)
       && ((*var->val.integer < 4) || (*var->val.integer > 1800))
     ) {
        rc = SNMP_ERR_WRONGVALUE;
    }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertMaxInterval",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertMaxInterval_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertMaxInterval_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertMinInterval(4)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTMININTERVAL:
    rc = netsnmp_check_vb_type_and_size( var, ASN_UNSIGNED,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertMinInterval ) );
    /* check defined range(s). */
    if( (SNMPERR_SUCCESS == rc)
       && ((*var->val.integer < 3) || (*var->val.integer > 1350))
     ) {
        rc = SNMP_ERR_WRONGVALUE;
    }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertMinInterval",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertMinInterval_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertMinInterval_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertManagedFlag(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTMANAGEDFLAG:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertManagedFlag ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != TRUTHVALUE_TRUE )
 && ( *var->val.integer != TRUTHVALUE_FALSE )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertManagedFlag",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertManagedFlag_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertManagedFlag_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertOtherConfigFlag(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertOtherConfigFlag ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != TRUTHVALUE_TRUE )
 && ( *var->val.integer != TRUTHVALUE_FALSE )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertOtherConfigFlag",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertOtherConfigFlag_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertOtherConfigFlag_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertLinkMTU(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTLINKMTU:
    rc = netsnmp_check_vb_type_and_size( var, ASN_UNSIGNED,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertLinkMTU ) );
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertLinkMTU",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertLinkMTU_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertLinkMTU_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertReachableTime(8)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTREACHABLETIME:
    rc = netsnmp_check_vb_type_and_size( var, ASN_UNSIGNED,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertReachableTime ) );
    /* check defined range(s). */
    if( (SNMPERR_SUCCESS == rc)
       && ((*var->val.integer < 0) || (*var->val.integer > 3600000))
     ) {
        rc = SNMP_ERR_WRONGVALUE;
    }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertReachableTime",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertReachableTime_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertReachableTime_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertRetransmitTime(9)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTRETRANSMITTIME:
    rc = netsnmp_check_vb_type_and_size( var, ASN_UNSIGNED,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertRetransmitTime ) );
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertRetransmitTime",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertRetransmitTime_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertRetransmitTime_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertCurHopLimit(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTCURHOPLIMIT:
    rc = netsnmp_check_vb_type_and_size( var, ASN_UNSIGNED,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertCurHopLimit ) );
    /* check defined range(s). */
    if( (SNMPERR_SUCCESS == rc)
       && ((*var->val.integer < 0) || (*var->val.integer > 255))
     ) {
        rc = SNMP_ERR_WRONGVALUE;
    }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertCurHopLimit",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertCurHopLimit_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertCurHopLimit_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertDefaultLifetime(11)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME:
    rc = netsnmp_check_vb_type_and_size( var, ASN_UNSIGNED,
        sizeof( rowreq_ctx->data.ipv6RouterAdvertDefaultLifetime ) );
    /* check defined range(s). */
    if( (SNMPERR_SUCCESS == rc)
       && (*var->val.integer != 0)
       && ((*var->val.integer < 4) || (*var->val.integer > 9000))
     ) {
        rc = SNMP_ERR_WRONGVALUE;
    }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertDefaultLifetime",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertDefaultLifetime_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertDefaultLifetime_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* ipv6RouterAdvertRowStatus(12)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_IPV6ROUTERADVERTROWSTATUS:
rc = netsnmp_check_vb_rowstatus_value(var);
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:_ipv6RouterAdvertTable_check_column:ipv6RouterAdvertRowStatus",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = ipv6RouterAdvertRowStatus_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from ipv6RouterAdvertRowStatus_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column %d in _ipv6RouterAdvertTable_check_column\n", column);
    }

    return rc;
} /* _ipv6RouterAdvertTable_check_column */

int
_mfd_ipv6RouterAdvertTable_check_objects(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_check_objects","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {

        /*
         * get column number from table request info, and check that column
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;

        rc = _ipv6RouterAdvertTable_check_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));
            break;
        }

    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_check_objects */


/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_ipv6RouterAdvertTable_undo_setup_column( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_ipv6RouterAdvertTable_undo_setup_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* ipv6RouterAdvertSendAdverts(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTSENDADVERTS:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTSENDADVERTS_FLAG;
        rc = ipv6RouterAdvertSendAdverts_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertMaxInterval(3)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTMAXINTERVAL:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMAXINTERVAL_FLAG;
        rc = ipv6RouterAdvertMaxInterval_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertMinInterval(4)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTMININTERVAL:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMININTERVAL_FLAG;
        rc = ipv6RouterAdvertMinInterval_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertManagedFlag(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTMANAGEDFLAG:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMANAGEDFLAG_FLAG;
        rc = ipv6RouterAdvertManagedFlag_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertOtherConfigFlag(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG_FLAG;
        rc = ipv6RouterAdvertOtherConfigFlag_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertLinkMTU(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTLINKMTU:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTLINKMTU_FLAG;
        rc = ipv6RouterAdvertLinkMTU_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertReachableTime(8)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTREACHABLETIME:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTREACHABLETIME_FLAG;
        rc = ipv6RouterAdvertReachableTime_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertRetransmitTime(9)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTRETRANSMITTIME:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTRETRANSMITTIME_FLAG;
        rc = ipv6RouterAdvertRetransmitTime_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertCurHopLimit(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTCURHOPLIMIT:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTCURHOPLIMIT_FLAG;
        rc = ipv6RouterAdvertCurHopLimit_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertDefaultLifetime(11)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME_FLAG;
        rc = ipv6RouterAdvertDefaultLifetime_undo_setup(rowreq_ctx );
        break;

    /* ipv6RouterAdvertRowStatus(12)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_IPV6ROUTERADVERTROWSTATUS:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTROWSTATUS_FLAG;
        rc = ipv6RouterAdvertRowStatus_undo_setup(rowreq_ctx );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _ipv6RouterAdvertTable_undo_setup_column\n", column);
         break;
    }

    return rc;
} /* _ipv6RouterAdvertTable_undo_setup_column */


/**
 * @internal
 * undo setup
 */
int
_mfd_ipv6RouterAdvertTable_undo_setup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_undo_setup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = ipv6RouterAdvertTable_allocate_data();
    if(NULL == rowreq_ctx->undo) {
        /** msg already logged */
        netsnmp_request_set_error_all(requests, SNMP_ERR_RESOURCEUNAVAILABLE);
        return SNMP_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = ipv6RouterAdvertTable_undo_setup(rowreq_ctx);
    if (MFD_SUCCESS != rc)  {
        DEBUGMSGTL(("ipv6RouterAdvertTable:mfd","error %d from "
                    "ipv6RouterAdvertTable_undo_setup\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    else {
        /*
         * column undo setup
         */
        netsnmp_table_request_info * tri;
        for(;requests; requests = requests->next) {
            /*
             * set column data
             */
            tri = netsnmp_extract_table_info(requests);
            if(NULL == tri)
                continue;
            
            rc = _ipv6RouterAdvertTable_undo_setup_column(rowreq_ctx, tri->colnum);
            if(MFD_SUCCESS != rc)  {
                DEBUGMSGTL(("ipv6RouterAdvertTable:mfd","error %d from "
                            "ipv6RouterAdvertTable_undo_setup_column\n", rc));
                netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
            }
        } /* for results */
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int
_mfd_ipv6RouterAdvertTable_undo_cleanup(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_undo_cleanup","called\n"));

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if (NULL == rowreq_ctx)
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = ipv6RouterAdvertTable_undo_cleanup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("ipv6RouterAdvertTable:mfd","error %d from "
                    "ipv6RouterAdvertTable_undo_cleanup\n", rc));
    }

    /*
     * release undo context, if needed
     */
    if(rowreq_ctx->undo) {
         ipv6RouterAdvertTable_release_data(rowreq_ctx->undo);
         rowreq_ctx->undo = NULL;
    }


    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_ipv6RouterAdvertTable_set_column( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_ipv6RouterAdvertTable_set_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* ipv6RouterAdvertSendAdverts(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTSENDADVERTS:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTSENDADVERTS_FLAG;
        rc = ipv6RouterAdvertSendAdverts_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertMaxInterval(3)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTMAXINTERVAL:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMAXINTERVAL_FLAG;
        rc = ipv6RouterAdvertMaxInterval_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertMinInterval(4)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTMININTERVAL:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMININTERVAL_FLAG;
        rc = ipv6RouterAdvertMinInterval_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertManagedFlag(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTMANAGEDFLAG:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTMANAGEDFLAG_FLAG;
        rc = ipv6RouterAdvertManagedFlag_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertOtherConfigFlag(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG_FLAG;
        rc = ipv6RouterAdvertOtherConfigFlag_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertLinkMTU(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTLINKMTU:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTLINKMTU_FLAG;
        rc = ipv6RouterAdvertLinkMTU_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertReachableTime(8)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTREACHABLETIME:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTREACHABLETIME_FLAG;
        rc = ipv6RouterAdvertReachableTime_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertRetransmitTime(9)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTRETRANSMITTIME:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTRETRANSMITTIME_FLAG;
        rc = ipv6RouterAdvertRetransmitTime_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertCurHopLimit(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTCURHOPLIMIT:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTCURHOPLIMIT_FLAG;
        rc = ipv6RouterAdvertCurHopLimit_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertDefaultLifetime(11)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME_FLAG;
        rc = ipv6RouterAdvertDefaultLifetime_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* ipv6RouterAdvertRowStatus(12)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_IPV6ROUTERADVERTROWSTATUS:
        rowreq_ctx->column_set_flags |= COLUMN_IPV6ROUTERADVERTROWSTATUS_FLAG;
        rc = ipv6RouterAdvertRowStatus_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _ipv6RouterAdvertTable_set_column\n", column);
         rc = SNMP_ERR_GENERR;
         break;
    }
    
    return rc;
} /* _ipv6RouterAdvertTable_set_column */

int
_mfd_ipv6RouterAdvertTable_set_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc = SNMP_ERR_NOERROR;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_set_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rowreq_ctx->column_set_flags = 0;
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _ipv6RouterAdvertTable_set_column(rowreq_ctx,
                                    requests->requestvb, tri->colnum);
        if(MFD_SUCCESS != rc)  {
            DEBUGMSGTL(("ipv6RouterAdvertTable:mfd","error %d from "
                        "ipv6RouterAdvertTable_set_column\n", rc));
            netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int
_mfd_ipv6RouterAdvertTable_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = ipv6RouterAdvertTable_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("ipv6RouterAdvertTable:mfd","error %d from "
                    "ipv6RouterAdvertTable_commit\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        ipv6RouterAdvertTable_dirty_set( ipv6RouterAdvertTable_dirty_get() + 1 ); /* set table dirty flag */
    }

    return SNMP_ERR_NOERROR;
}

int
_mfd_ipv6RouterAdvertTable_undo_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_undo_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        u_int  d = ipv6RouterAdvertTable_dirty_get();

        netsnmp_assert(d != 0);
        if(d)
            ipv6RouterAdvertTable_dirty_set( d - 1 );
    }

    rc = ipv6RouterAdvertTable_undo_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("ipv6RouterAdvertTable:mfd","error %d from "
                    "ipv6RouterAdvertTable_undo_commit\n", rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        snmp_log(LOG_WARNING, "ipv6RouterAdvertTable row dirty flag still set after undo_commit\n");
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_ipv6RouterAdvertTable_undo_column( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_ipv6RouterAdvertTable_undo_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* ipv6RouterAdvertSendAdverts(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTSENDADVERTS:
        rc = ipv6RouterAdvertSendAdverts_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertMaxInterval(3)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTMAXINTERVAL:
        rc = ipv6RouterAdvertMaxInterval_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertMinInterval(4)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTMININTERVAL:
        rc = ipv6RouterAdvertMinInterval_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertManagedFlag(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTMANAGEDFLAG:
        rc = ipv6RouterAdvertManagedFlag_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertOtherConfigFlag(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h */
    case COLUMN_IPV6ROUTERADVERTOTHERCONFIGFLAG:
        rc = ipv6RouterAdvertOtherConfigFlag_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertLinkMTU(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTLINKMTU:
        rc = ipv6RouterAdvertLinkMTU_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertReachableTime(8)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h */
    case COLUMN_IPV6ROUTERADVERTREACHABLETIME:
        rc = ipv6RouterAdvertReachableTime_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertRetransmitTime(9)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h */
    case COLUMN_IPV6ROUTERADVERTRETRANSMITTIME:
        rc = ipv6RouterAdvertRetransmitTime_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertCurHopLimit(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTCURHOPLIMIT:
        rc = ipv6RouterAdvertCurHopLimit_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertDefaultLifetime(11)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h */
    case COLUMN_IPV6ROUTERADVERTDEFAULTLIFETIME:
        rc = ipv6RouterAdvertDefaultLifetime_undo(rowreq_ctx);
        break;

    /* ipv6RouterAdvertRowStatus(12)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_IPV6ROUTERADVERTROWSTATUS:
        rc = ipv6RouterAdvertRowStatus_undo(rowreq_ctx);
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _ipv6RouterAdvertTable_undo_column\n", column);
         break;
    }

    return rc;
} /* _ipv6RouterAdvertTable_undo_column */

int
_mfd_ipv6RouterAdvertTable_undo_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;

    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_undo_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = ipv6RouterAdvertTable_undo(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("ipv6RouterAdvertTable:mfd","error %d from "
                    "ipv6RouterAdvertTable_undo\n", rc));
    }
    
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _ipv6RouterAdvertTable_undo_column(rowreq_ctx, requests->requestvb,
                                     tri->colnum);
        if (MFD_SUCCESS != rc) {
            /*
             * nothing we can do about it but log it
             */
            DEBUGMSGTL(("ipv6RouterAdvertTable:mfd","error %d from "
                        "ipv6RouterAdvertTable_undo_column\n", rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int
_mfd_ipv6RouterAdvertTable_irreversible_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_mfd_ipv6RouterAdvertTable_irreversible:commit","called\n"));
   
    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
        if (! (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED))
            CONTAINER_REMOVE(ipv6RouterAdvertTable_if_ctx.container, rowreq_ctx);
    }
    else {
        if (rowreq_ctx->column_set_flags) {
           rowreq_ctx->column_set_flags = 0;
        }
        if (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED) {
            rowreq_ctx->rowreq_flags &= ~MFD_ROW_CREATED;
            CONTAINER_INSERT(ipv6RouterAdvertTable_if_ctx.container, rowreq_ctx);
        }
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_ipv6RouterAdvertTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
/**
 * @internal
 */
static void
_container_item_free(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    ipv6RouterAdvertTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in ipv6RouterAdvertTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    ipv6RouterAdvertTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_ipv6RouterAdvertTable_container_init(ipv6RouterAdvertTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_ipv6RouterAdvertTable_container_init","called\n"));

    /*
     * container init
     */    
    ipv6RouterAdvertTable_container_init(&if_ctx->container);
    if(NULL == if_ctx->container)
        if_ctx->container = netsnmp_container_find("ipv6RouterAdvertTable:table_container");
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "ipv6RouterAdvertTable_container_init\n");
        return;
    }

} /* _ipv6RouterAdvertTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_ipv6RouterAdvertTable_container_shutdown(ipv6RouterAdvertTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:ipv6RouterAdvertTable:_ipv6RouterAdvertTable_container_shutdown","called\n"));

    ipv6RouterAdvertTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _ipv6RouterAdvertTable_container_shutdown */


ipv6RouterAdvertTable_rowreq_ctx *
ipv6RouterAdvertTable_row_find_by_mib_index(ipv6RouterAdvertTable_mib_index *mib_idx)
{
    ipv6RouterAdvertTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = ipv6RouterAdvertTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = (ipv6RouterAdvertTable_rowreq_ctx*)CONTAINER_FIND(ipv6RouterAdvertTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}

