/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef IPV6ROUTERADVERTTABLE_H
#define IPV6ROUTERADVERTTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(ip-mib)
config_require(ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable_interface)
config_require(ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable_data_access)
config_require(ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable_data_get)
config_require(ip-mib/ipv6RouterAdvertTable/ipv6RouterAdvertTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for ipv6RouterAdvertTable */
#include "ipv6RouterAdvertTable_oids.h"

/* enum definions */
#include "ipv6RouterAdvertTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_ipv6RouterAdvertTable(void);
void shutdown_ipv6RouterAdvertTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ipv6RouterAdvertTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-MIB::ipv6RouterAdvertTable is subid 39 of ip.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.39, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review ipv6RouterAdvertTable registration context.
     */
typedef netsnmp_data_list ipv6RouterAdvertTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review ipv6RouterAdvertTable data context structure.
 * This structure is used to represent the data for ipv6RouterAdvertTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * ipv6RouterAdvertTable.
 */
typedef struct ipv6RouterAdvertTable_data_s {
    
        /*
         * ipv6RouterAdvertSendAdverts(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
         */
   u_long   ipv6RouterAdvertSendAdverts;
    
        /*
         * ipv6RouterAdvertMaxInterval(3)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h
         */
   u_long   ipv6RouterAdvertMaxInterval;
    
        /*
         * ipv6RouterAdvertMinInterval(4)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h
         */
   u_long   ipv6RouterAdvertMinInterval;
    
        /*
         * ipv6RouterAdvertManagedFlag(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
         */
   u_long   ipv6RouterAdvertManagedFlag;
    
        /*
         * ipv6RouterAdvertOtherConfigFlag(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
         */
   u_long   ipv6RouterAdvertOtherConfigFlag;
    
        /*
         * ipv6RouterAdvertLinkMTU(7)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h
         */
   u_long   ipv6RouterAdvertLinkMTU;
    
        /*
         * ipv6RouterAdvertReachableTime(8)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/D/h
         */
   u_long   ipv6RouterAdvertReachableTime;
    
        /*
         * ipv6RouterAdvertRetransmitTime(9)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/h
         */
   u_long   ipv6RouterAdvertRetransmitTime;
    
        /*
         * ipv6RouterAdvertCurHopLimit(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h
         */
   u_long   ipv6RouterAdvertCurHopLimit;
    
        /*
         * ipv6RouterAdvertDefaultLifetime(11)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/R/d/h
         */
   u_long   ipv6RouterAdvertDefaultLifetime;
    
        /*
         * ipv6RouterAdvertRowStatus(12)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   ipv6RouterAdvertRowStatus;
    
} ipv6RouterAdvertTable_data;


/* *********************************************************************
 * TODO:115:o: |-> Review ipv6RouterAdvertTable undo context.
 * We're just going to use the same data structure for our
 * undo_context. If you want to do something more efficent,
 * define your typedef here.
 */
typedef ipv6RouterAdvertTable_data ipv6RouterAdvertTable_undo_data;

/*
 * TODO:120:r: |-> Review ipv6RouterAdvertTable mib index.
 * This structure is used to represent the index for ipv6RouterAdvertTable.
 */
typedef struct ipv6RouterAdvertTable_mib_index_s {

        /*
         * ipv6RouterAdvertIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H
         */
   long   ipv6RouterAdvertIfIndex;


} ipv6RouterAdvertTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review ipv6RouterAdvertTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_ipv6RouterAdvertTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review ipv6RouterAdvertTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * ipv6RouterAdvertTable_rowreq_ctx pointer.
 */
typedef struct ipv6RouterAdvertTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_ipv6RouterAdvertTable_IDX_LEN];
    
    ipv6RouterAdvertTable_mib_index        tbl_idx;
    
    ipv6RouterAdvertTable_data              data;
    ipv6RouterAdvertTable_undo_data       * undo;
    unsigned int                column_set_flags; /* flags for set columns */


    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to ipv6RouterAdvertTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *ipv6RouterAdvertTable_data_list;

} ipv6RouterAdvertTable_rowreq_ctx;

typedef struct ipv6RouterAdvertTable_ref_rowreq_ctx_s {
    ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx;
} ipv6RouterAdvertTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int ipv6RouterAdvertTable_pre_request(ipv6RouterAdvertTable_registration * user_context);
    int ipv6RouterAdvertTable_post_request(ipv6RouterAdvertTable_registration * user_context,
        int rc);

    int ipv6RouterAdvertTable_rowreq_ctx_init(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void ipv6RouterAdvertTable_rowreq_ctx_cleanup(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);

    int ipv6RouterAdvertTable_commit(ipv6RouterAdvertTable_rowreq_ctx * rowreq_ctx);

    ipv6RouterAdvertTable_rowreq_ctx *
                  ipv6RouterAdvertTable_row_find_by_mib_index(ipv6RouterAdvertTable_mib_index *mib_idx);

extern const oid ipv6RouterAdvertTable_oid[];
extern const int ipv6RouterAdvertTable_oid_size;


#include "ipv6RouterAdvertTable_interface.h"
#include "ipv6RouterAdvertTable_data_access.h"
#include "ipv6RouterAdvertTable_data_get.h"
#include "ipv6RouterAdvertTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* IPV6ROUTERADVERTTABLE_H */
/** @} */
