/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef IPV6ROUTERADVERTTABLE_INTERFACE_H
#define IPV6ROUTERADVERTTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "ipv6RouterAdvertTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _ipv6RouterAdvertTable_initialize_interface(ipv6RouterAdvertTable_registration * user_ctx,
                                    u_long flags);
void _ipv6RouterAdvertTable_shutdown_interface(ipv6RouterAdvertTable_registration * user_ctx);

ipv6RouterAdvertTable_registration *
ipv6RouterAdvertTable_registration_get( void );

ipv6RouterAdvertTable_registration *
ipv6RouterAdvertTable_registration_set( ipv6RouterAdvertTable_registration * newreg );

netsnmp_container *ipv6RouterAdvertTable_container_get( void );
int ipv6RouterAdvertTable_container_size( void );

u_int ipv6RouterAdvertTable_dirty_get( void );
void ipv6RouterAdvertTable_dirty_set( u_int status );

    ipv6RouterAdvertTable_rowreq_ctx * ipv6RouterAdvertTable_allocate_rowreq_ctx(void *);
void ipv6RouterAdvertTable_release_rowreq_ctx(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);

int ipv6RouterAdvertTable_index_to_oid(netsnmp_index *oid_idx,
                            ipv6RouterAdvertTable_mib_index *mib_idx);
int ipv6RouterAdvertTable_index_from_oid(netsnmp_index *oid_idx,
                              ipv6RouterAdvertTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void ipv6RouterAdvertTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* IPV6ROUTERADVERTTABLE_INTERFACE_H */
/** @} */
