/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for ipv6RouterAdvertTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ipv6RouterAdvertTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "ipv6RouterAdvertTable_interface.h"

const oid ipv6RouterAdvertTable_oid[] = { IPV6ROUTERADVERTTABLE_OID };
const int ipv6RouterAdvertTable_oid_size = OID_LENGTH(ipv6RouterAdvertTable_oid);

    ipv6RouterAdvertTable_registration  ipv6RouterAdvertTable_user_context;

void initialize_table_ipv6RouterAdvertTable(void);
void shutdown_table_ipv6RouterAdvertTable(void);


/**
 * Initializes the ipv6RouterAdvertTable module
 */
void
init_ipv6RouterAdvertTable(void)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:init_ipv6RouterAdvertTable","called\n"));

    /*
     * TODO:300:o: Perform ipv6RouterAdvertTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("ipv6RouterAdvertTable"))
        initialize_table_ipv6RouterAdvertTable();

} /* init_ipv6RouterAdvertTable */

/**
 * Shut-down the ipv6RouterAdvertTable module (agent is exiting)
 */
void
shutdown_ipv6RouterAdvertTable(void)
{
    if (should_init("ipv6RouterAdvertTable"))
        shutdown_table_ipv6RouterAdvertTable();

}

/**
 * Initialize the table ipv6RouterAdvertTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_ipv6RouterAdvertTable(void)
{
    ipv6RouterAdvertTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:initialize_table_ipv6RouterAdvertTable","called\n"));

    /*
     * TODO:301:o: Perform ipv6RouterAdvertTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize ipv6RouterAdvertTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("ipv6RouterAdvertTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _ipv6RouterAdvertTable_initialize_interface(user_context, flags);
} /* initialize_table_ipv6RouterAdvertTable */

/**
 * Shutdown the table ipv6RouterAdvertTable 
 */
void
shutdown_table_ipv6RouterAdvertTable(void)
{
    /*
     * call interface shutdown code
     */
    _ipv6RouterAdvertTable_shutdown_interface(&ipv6RouterAdvertTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
ipv6RouterAdvertTable_rowreq_ctx_init(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra ipv6RouterAdvertTable rowreq initialization. (eg DEFVALS)
     */
    rowreq_ctx->data.ipv6RouterAdvertSendAdverts = TRUTHVALUE_FALSE;
    
    rowreq_ctx->data.ipv6RouterAdvertMaxInterval = 600;
    
    rowreq_ctx->data.ipv6RouterAdvertManagedFlag = TRUTHVALUE_FALSE;
    
    rowreq_ctx->data.ipv6RouterAdvertOtherConfigFlag = TRUTHVALUE_FALSE;
    
    rowreq_ctx->data.ipv6RouterAdvertLinkMTU = 0;
    
    rowreq_ctx->data.ipv6RouterAdvertReachableTime = 0;
    
    rowreq_ctx->data.ipv6RouterAdvertRetransmitTime = 0;
    

    return MFD_SUCCESS;
} /* ipv6RouterAdvertTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void ipv6RouterAdvertTable_rowreq_ctx_cleanup(ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra ipv6RouterAdvertTable rowreq cleanup.
     */
} /* ipv6RouterAdvertTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
ipv6RouterAdvertTable_pre_request(ipv6RouterAdvertTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform ipv6RouterAdvertTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* ipv6RouterAdvertTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
ipv6RouterAdvertTable_post_request(ipv6RouterAdvertTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:ipv6RouterAdvertTable:ipv6RouterAdvertTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform ipv6RouterAdvertTable post-request actions.
     */

    /*
     * check to set if any rows were changed.
     */
    if (ipv6RouterAdvertTable_dirty_get()) {
        /*
         * check if request was successful. If so, this would be
         * a good place to save data to its persistent store.
         */
        if (MFD_SUCCESS == rc) {
            /*
             * save changed rows, if you haven't already
             */
        }
        
        ipv6RouterAdvertTable_dirty_set(0); /* clear table dirty flag */
    }

    return MFD_SUCCESS;
} /* ipv6RouterAdvertTable_post_request */


/** @{ */
