/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef IPV6ROUTERADVERTTABLE_DATA_SET_H
#define IPV6ROUTERADVERTTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ipv6RouterAdvertTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-MIB::ipv6RouterAdvertTable is subid 39 of ip.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.39, length: 8
*/


int ipv6RouterAdvertTable_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);
int ipv6RouterAdvertTable_undo_cleanup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);
int ipv6RouterAdvertTable_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);
int ipv6RouterAdvertTable_commit( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);
int ipv6RouterAdvertTable_undo_commit( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx);


int ipv6RouterAdvertSendAdverts_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertSendAdverts_val);
int ipv6RouterAdvertSendAdverts_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertSendAdverts_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertSendAdverts_val );
int ipv6RouterAdvertSendAdverts_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertMaxInterval_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertMaxInterval_val);
int ipv6RouterAdvertMaxInterval_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertMaxInterval_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertMaxInterval_val );
int ipv6RouterAdvertMaxInterval_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertMinInterval_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertMinInterval_val);
int ipv6RouterAdvertMinInterval_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertMinInterval_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertMinInterval_val );
int ipv6RouterAdvertMinInterval_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertManagedFlag_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertManagedFlag_val);
int ipv6RouterAdvertManagedFlag_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertManagedFlag_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertManagedFlag_val );
int ipv6RouterAdvertManagedFlag_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertOtherConfigFlag_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertOtherConfigFlag_val);
int ipv6RouterAdvertOtherConfigFlag_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertOtherConfigFlag_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertOtherConfigFlag_val );
int ipv6RouterAdvertOtherConfigFlag_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertLinkMTU_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertLinkMTU_val);
int ipv6RouterAdvertLinkMTU_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertLinkMTU_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertLinkMTU_val );
int ipv6RouterAdvertLinkMTU_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertReachableTime_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertReachableTime_val);
int ipv6RouterAdvertReachableTime_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertReachableTime_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertReachableTime_val );
int ipv6RouterAdvertReachableTime_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertRetransmitTime_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertRetransmitTime_val);
int ipv6RouterAdvertRetransmitTime_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertRetransmitTime_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertRetransmitTime_val );
int ipv6RouterAdvertRetransmitTime_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertCurHopLimit_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertCurHopLimit_val);
int ipv6RouterAdvertCurHopLimit_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertCurHopLimit_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertCurHopLimit_val );
int ipv6RouterAdvertCurHopLimit_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertDefaultLifetime_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertDefaultLifetime_val);
int ipv6RouterAdvertDefaultLifetime_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertDefaultLifetime_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertDefaultLifetime_val );
int ipv6RouterAdvertDefaultLifetime_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );

int ipv6RouterAdvertRowStatus_check_value( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertRowStatus_val);
int ipv6RouterAdvertRowStatus_undo_setup( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );
int ipv6RouterAdvertRowStatus_set( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx, u_long ipv6RouterAdvertRowStatus_val );
int ipv6RouterAdvertRowStatus_undo( ipv6RouterAdvertTable_rowreq_ctx *rowreq_ctx );


int ipv6RouterAdvertTable_check_dependencies(ipv6RouterAdvertTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* IPV6ROUTERADVERTTABLE_DATA_SET_H */
