CONFIG_USB_MU3H=y
CONFIG_USB_MU3H_DRV=y

export CONFIG_USB_MU3H
export CONFIG_USB_MU3H_DRV

obj-$(CONFIG_USB_MU3H)	+= mu3h_lib/
obj-$(CONFIG_USB_MU3H_DRV)	+= mu3h_drv/
#obj-$(CONFIG_USB_MU3H_TEST_DRV)	+= mu3h_test_drv/


