#ifndef _SGMII_REG_H_
#define _SGMII_REG_H_
	
	//======================================================================
	//AN
	//======================================================================
#define 	 SGMII_REG_AN0                           (0x0000)
#define 	 SGMII_REG_AN_1                          (0x0004)
#define 	 SGMII_REG_AN_2                          (0x0008)
#define 	 SGMII_REG_AN_3                          (0x000c)
#define 	 SGMII_REG_AN_4                          (0x0010)
#define 	 SGMII_REG_AN_5                          (0x0014)
#define 	 SGMII_REG_AN_6                          (0x0018)
#define 	 SGMII_REG_AN_7                          (0x001c)
#define 	 SGMII_REG_AN_8                          (0x0020)
#define 	 SGMII_REG_AN_9                          (0x0024)
#define 	 SGMII_REG_AN_10                         (0x0028)
#define 	 SGMII_REG_AN_11                         (0x002c)
#define 	 SGMII_REG_AN_12                         (0x0030)
#define 	 SGMII_REG_AN_13                         (0x0034)
#define 	 SGMII_REG_AN_14                         (0x0038)
#define 	 SGMII_REG_AN_15                         (0x003c)
#define 	 SGMII_REG_AN_16                         (0x0040)
#define 	 SGMII_REG_AN_17                         (0x0044)
#define 	 SGMII_REG_AN_18                         (0x0048)
#define 	 SGMII_REG_AN_19                         (0x004c)
#define 	 SGMII_REG_AN_20                         (0x0050)
#define 	 SGMII_REG_AN_21                         (0x0054)
#define 	 SGMII_REG_AN_22                         (0x0058)
#define 	 SGMII_REG_AN_FORCE_CL37                 (0x0060)
	
	
	//======================================================================
	//RATE_ADAPT
	//======================================================================
#define 	 SGMII_RG_RATE_ADAPT_CTRL_0              (0x0000)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_1              (0x0004)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_2              (0x0008)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_3              (0x000c)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_4              (0x0010)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_5              (0x0014)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_6              (0x0018)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_7              (0x001c)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_8              (0x0020)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_9              (0x0024)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_10             (0x0028)
#define 	 SGMII_RG_RATE_ADAPT_CTRL_11             (0x002c)
#define 	 SGMII_RO_RATE_ADAPT_STS_0               (0x0030)
#define 	 SGMII_RO_RATE_ADAPT_STS_1               (0x0034)
#define 	 SGMII_RO_RATE_ADAPT_STS_2               (0x0038)
#define 	 SGMII_RO_RATE_ADAPT_STS_3               (0x003c)
#define 	 SGMII_RO_RATE_ADAPT_STS_4               (0x0040)
#define 	 SGMII_RO_RATE_ADAPT_STS_5               (0x0044)
#define 	 SGMII_RO_RATE_ADAPT_STS_6               (0x0048)
#define 	 SGMII_RO_RATE_ADAPT_STS_7               (0x004c)
#define 	 SGMII_RO_RATE_ADAPT_STS_8               (0x0050)
#define 	 SGMII_RO_RATE_ADAPT_STS_9               (0x0054)
#define 	 SGMII_RO_RATE_ADAPT_STS_10              (0x0058)
#define 	 SGMII_RO_RATE_ADAPT_STS_11              (0x005c)
#define 	 SGMII_RO_RATE_ADAPT_STS_12              (0x0060)
#define 	 SGMII_RG_RATE_ADAPT_OUT_CNT_RESET       (0x00a0)
#define 	 SGMII_RO_RATE_ADAPT_OUT_CNT_PRE6        (0x00a4)
#define 	 SGMII_RO_RATE_ADAPT_OUT_CNT_PRE5        (0x00a8)
#define 	 SGMII_RG_FPGA_MODE_SET                  (0x00ac)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_0_STS          (0x00b0)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_1_STS          (0x00b4)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_2_STS          (0x00b8)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_3_STS          (0x00bc)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_4_STS          (0x00c0)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_5_STS          (0x00c4)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_6_STS          (0x00c8)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_7_STS          (0x00cc)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_8_STS          (0x00d0)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_9_STS          (0x00d4)
#define 	 SGMII_RO_RATE_ADAPT_CTRL_10_STS         (0x00d8)
	
	
	//======================================================================
	//PCS2
	//======================================================================
#define 	 SGMII_RG_HSGMII_PCS_CTROL_1             (0x0a00)
#define 	 SGMII_RG_HSGMII_PCS_CTROL_2             (0x0a04)
#define 	 SGMII_RG_HSGMII_PCS_CTROL_3             (0x0a08)
#define 	 SGMII_RG_HSGMII_PCS_CTROL_4             (0x0a0c)
#define 	 SGMII_RG_HSGMII_PCS_CTROL_5             (0x0a10)
#define 	 SGMII_RG_HSGMII_PCS_CTROL_6             (0x0a14)
#define 	 SGMII_RG_HSGMII_PCS_GPII_0              (0x0a18)
#define 	 SGMII_RG_HSGMII_MODE_PROBE_SEL          (0x0a1c)
#define 	 SGMII_RG_HSGMII_MODE_INTERRUPT          (0x0a20)
#define 	 SGMII_RG_HSGMII_PCS_GPII_1              (0x0a24)
#define 	 SGMII_RG_HSGMII_PCS_GPII_2              (0x0a28)
#define 	 SGMII_RG_HSGMII_PCS_GPII_3              (0x0a2c)
#define 	 SGMII_RG_HSGMII_PCS_GPII_4              (0x0a30)
#define 	 SGMII_RG_HSGMII_PCS_GPII_5              (0x0a34)
#define 	 SGMII_RG_HSGMII_PCS_STATE_1             (0x0b00)
#define 	 SGMII_RG_HSGMII_PCS_STATE_2             (0x0b04)
#define 	 SGMII_RG_HSGMII_PCS_STATE_3             (0x0b08)
#define 	 SGMII_RG_HSGMII_PCS_STATE_4             (0x0b0c)
#define 	 SGMII_RG_HSGMII_PCS_STATE_5             (0x0b10)
#define 	 SGMII_RG_HSGMII_PCS_STATE_6             (0x0b14)
#define 	 SGMII_RG_HSGMII_PCS_STATE_7             (0x0b18)
#define 	 SGMII_RG_HSGMII_PCS_STATE_8             (0x0b1c)
#define 	 SGMII_RG_HSGMII_GPII_STATE_1            (0x0b20)
#define 	 SGMII_RG_HSGMII_GPII_STATE_2            (0x0b28)
#define 	 SGMII_RG_HSGMII_GPII_STATE_3            (0x0b2c)
#define 	 SGMII_RG_HSGMII_GPII_STATE_4            (0x0b30)
#define 	 SGMII_RG_HSGMII_GPII_STATE_5            (0x0b34)
#define 	 SGMII_RG_HSGMII_GPII_STATE_6            (0x0b38)
#define 	 SGMII_RG_HSGMII_GPII_STATE_7            (0x0b3c)
#define 	 SGMII_RG_HSGMII_GPII_STATE_8            (0x0b40)
#define 	 SGMII_RG_HSGMII_GPII_STATE_9            (0x0b44)
#define 	 SGMII_RG_HSGMII_GPII_STATE_10           (0x0b48)
#define 	 SGMII_RG_HSGMII_GPII_STATE_11           (0x0b4c)
#define 	 SGMII_RG_HSGMII_GPII_STATE_12           (0x0b50)
#define 	 SGMII_RG_HSGMII_GPII_STATE_13           (0x0b54)
#define 	 SGMII_RG_HSGMII_PCS_STATE_9             (0x0b58)
#define 	 SGMII_RG_HSGMII_PCS_INT_STATE           (0x0b5c)
	
	
	
	
//======================================================================
//PHYA
//======================================================================
	
#define 	 SGMII_REG_PHYA_0                        (0x0000)
#define 	 SGMII_REG_PHYA_1                        (0x0004)
#define 	 SGMII_REG_PHYA_2                        (0x0008)
#define 	 SGMII_REG_PHYA_3                        (0x000c)
#define 	 SGMII_REG_PHYA_4                        (0x0010)
#define 	 SGMII_REG_PHYA_5                        (0x0014)
#define 	 SGMII_REG_PHYA_6                        (0x0018)
#define 	 SGMII_REG_PHYA_7                        (0x001c)
#define 	 SGMII_REG_PHYA_8                        (0x0020)
#define 	 SGMII_REG_PHYA_9                        (0x0024)
#define 	 SGMII_REG_PHYA_10                       (0x0028)
#define 	 SGMII_REG_PHYA_11                       (0x002c)
#define 	 SGMII_REG_PHYA_12                       (0x0030)
#define 	 SGMII_REG_PHYA_13                       (0x0034)
#define 	 SGMII_REG_PHYA_14                       (0x0038)
#define 	 SGMII_REG_PHYA_15                       (0x003c)
#define 	 SGMII_REG_PHYA_16                       (0x0040)
#define 	 SGMII_REG_PHYA_17                       (0x0044)
#define 	 SGMII_REG_PHYA_18                       (0x0048)
#define 	 SGMII_REG_PHYA_19                       (0x004c)
#define 	 SGMII_REG_PHYA_20                       (0x0050)
#define 	 SGMII_REG_PHYA_21                       (0x0054)
#define 	 SGMII_REG_PHYA_22                       (0x0058)
#define 	 SGMII_REG_PHYA_23                       (0x005c)
#define 	 SGMII_REG_PHYA_24                       (0x0060)
#define 	 SGMII_REG_PHYA_25                       (0x0064)
#define 	 SGMII_REG_PHYA_26                       (0x0068)
#define 	 SGMII_REG_PHYA_27                       (0x006c)
#define 	 SGMII_REG_PHYA_28                       (0x0070)
#define 	 SGMII_REG_PHYA_29                       (0x0074)
#define 	 SGMII_REG_PHYA_30                       (0x0078)
#define 	 SGMII_REG_PHYA_31                       (0x007c)
#define 	 SGMII_REG_PHYA_32                       (0x0080)
#define 	 SGMII_REG_PHYA_33                       (0x0084)
#define 	 SGMII_REG_PHYA_34                       (0x0088)
#define 	 SGMII_REG_PHYA_35                       (0x008c)
#define 	 SGMII_REG_PHYA_36                       (0x0090)
#define 	 SGMII_REG_PHYA_37                       (0x0094)
#define 	 SGMII_REG_PHYA_38                       (0x0098)
#define 	 SGMII_REG_PHYA_39                       (0x009c)
#define 	 SGMII_REG_PHYA_40                       (0x00a0)
#define 	 SGMII_REG_PHYA_41                       (0x00a4)
#define 	 SGMII_REG_PHYA_42                       (0x00a8)
#define 	 SGMII_REG_PHYA_43                       (0x00ac)
#define 	 SGMII_REG_PHYA_44                       (0x00b0)
#define 	 SGMII_REG_PHYA_45                       (0x00b4)
#define 	 SGMII_REG_PHYA_46                       (0x00b8)
#define 	 SGMII_REG_PHYA_47                       (0x00bc)
#define 	 SGMII_REG_PHYA_48                       (0x00c0)
#define 	 SGMII_REG_PHYA_49                       (0x00c4)
#define 	 SGMII_REG_PHYA_50                       (0x00c8)
#define 	 SGMII_REG_PHYA_51                       (0x00cc)
#define 	 SGMII_REG_PHYA_52                       (0x00d0)
#define 	 SGMII_REG_PHYA_53                       (0x00d4)
#define 	 SGMII_REG_PHYA_54                       (0x00d8)
#define 	 SGMII_REG_PHYA_55                       (0x00dc)
#define 	 SGMII_REG_PHYA_56                       (0x00e0)
#define 	 SGMII_REG_PHYA_57                       (0x00e4)
#define 	 SGMII_REG_PHYA_58                       (0x00e8)
#define 	 SGMII_REG_PHYA_59                       (0x00ec)
#define 	 SGMII_REG_PHYA_60                       (0x00f0)
#define 	 SGMII_REG_PHYA_61                       (0x00f4)
#define 	 SGMII_REG_PHYA_62                       (0x00f8)
#define 	 SGMII_REG_PHYA_63                       (0x00fc)
#define 	 SGMII_REG_PHYA_64                       (0x0100)
#define 	 SGMII_REG_PHYA_65                       (0x0104)
#define 	 SGMII_REG_PHYA_66                       (0x0108)
#define 	 SGMII_REG_PHYA_67                       (0x010c)
#define 	 SGMII_REG_PHYA_68                       (0x0110)
#define 	 SGMII_REG_PHYA_69                       (0x0114)
#define 	 SGMII_REG_PHYA_70                       (0x0118)
#define 	 SGMII_REG_PHYA_71                       (0x011c)
#define 	 SGMII_REG_PHYA_72                       (0x0120)
#define 	 SGMII_REG_PHYA_73                       (0x0124)
#define 	 SGMII_REG_PHYA_74                       (0x0128)
#define 	 SGMII_REG_PHYA_75                       (0x012c)
#define 	 SGMII_REG_PHYA_76                       (0x0130)
#define 	 SGMII_REG_PHYA_77                       (0x0134)
#define 	 SGMII_REG_PHYA_78                       (0x0138)
#define 	 SGMII_REG_PHYA_79                       (0x013c)
#define 	 SGMII_REG_PHYA_80                       (0x0140)
#define 	 SGMII_REG_PHYA_81                       (0x0144)
#define 	 SGMII_REG_PHYA_82                       (0x0148)
#define 	 SGMII_REG_INTERRUPT_SEL                 (0x014c)
#define 	 SGMII_REG_PROBE_SEL                     (0x0150)
#define 	 SGMII_FPGA_MODE_CONTROL                 (0x0154)
#define 	 SGMII_ASYNC_FIFO_CONTROL                (0x0158)
#define 	 SGMII_REG_DWN_SHIFT_CTRL                (0x015c)
#define 	 SGMII_REG_DWN_SHIFT_TIMER_CTRL          (0x0160)
#define 	 SGMII_RO_DWN_SHIFT_STATUS               (0x0164)
#define 	 SGMII_RO_PHYA_0                         (0x0200)
#define 	 SGMII_RO_PHYA_1                         (0x0204)
#define 	 SGMII_RO_PHYA_2                         (0x0208)
#define 	 SGMII_RO_PHYA_3                         (0x020c)
#define 	 SGMII_RO_PHYA_4                         (0x0210)
#define 	 SGMII_RO_PHYA_5                         (0x0214)
#define 	 SGMII_RO_PHYA_6                         (0x0218)
#define 	 SGMII_RO_PHYA_7                         (0x021c)
#define 	 SGMII_RO_PHYA_8                         (0x0220)
#define 	 SGMII_RO_PHYA_9                         (0x0224)
#define 	 SGMII_RO_PHYA_10                        (0x0228)
#define 	 SGMII_RO_PHYA_11                        (0x022c)
#define 	 SGMII_RO_PHYA_12                        (0x0230)
#define 	 SGMII_RO_PHYA_13                        (0x0234)
#define 	 SGMII_RO_PHYA_14                        (0x0238)
#define 	 SGMII_RO_PHYA_15                        (0x023c)
#define 	 SGMII_RO_PHYA_16                        (0x0240)
#define 	 SGMII_RO_PHYA_17                        (0x0244)
#define 	 SGMII_RO_PHYA_18                        (0x0248)
#define 	 SGMII_RO_PHYA_19                        (0x024c)
#define 	 SGMII_RO_PHYA_20                        (0x0250)
#define 	 SGMII_RO_PHYA_21                        (0x0254)
#define 	 SGMII_RO_PHYA_22                        (0x0258)
#define 	 SGMII_RO_PHYA_23                        (0x025c)
#define 	 SGMII_RO_PHYA_24                        (0x0260)
#define 	 SGMII_RO_PHYA_25                        (0x0264)
#define 	 SGMII_RO_PHYA_26                        (0x0268)
#define 	 SGMII_RO_PHYA_AFIFO                     (0x026c)
#define 	 SGMII_RO_PHYA_AFIFO_CNT_0               (0x0270)
#define 	 SGMII_RO_PHYA_AFIFO_CNT_1               (0x0274)
#define 	 SGMII_RO_PHYA_AFIFO_CNT_2               (0x0278)
#define 	 SGMII_RO_PHYA_AFIFO_CNT_3               (0x027c)
#define 	 SGMII_LED_CTRL                          (0x0300)
#define 	 SGMII_LED_DUR                           (0x0304)
#define 	 SGMII_LED01_MASK                        (0x0308)
#define 	 SGMII_LED23_MASK                        (0x030c)
#define 	 SGMII_LED_EVENT_STATUS                  (0x0310)
#define 	 SGMII_DEBUG_DATA_CTRL                   (0x0320)
#define 	 SGMII_DEBUG_DATA_DUMP_0                 (0x0324)
#define 	 SGMII_DEBUG_DATA_DUMP_1                 (0x0328)
#define 	 SGMII_DEBUG_DATA_DUMP_2                 (0x032c)
#define 	 SGMII_DEBUG_DATA_DUMP_3                 (0x0330)
#define 	 SGMII_DEBUG_DATA_DUMP_4                 (0x0334)
#define 	 SGMII_DEBUG_DATA_DUMP_5                 (0x0338)
#define 	 SGMII_DEBUG_DATA_DUMP_6                 (0x033c)
#define 	 SGMII_DEBUG_DATA_DUMP_7                 (0x0340)
#define 	 SGMII_DEBUG_DATA_DUMP_8                 (0x0344)
#define 	 SGMII_DEBUG_DATA_DUMP_9                 (0x0348)
#define 	 SGMII_DEBUG_DATA_DUMP_10                (0x034c)
#define 	 SGMII_DEBUG_DATA_DUMP_11                (0x0350)
#define 	 SGMII_DEBUG_DATA_DUMP_12                (0x0354)
#define 	 SGMII_DEBUG_DATA_DUMP_13                (0x0358)
#define 	 SGMII_DEBUG_DATA_DUMP_14                (0x035c)
#define 	 SGMII_DEBUG_DATA_DUMP_15                (0x0360)
#define 	 SGMII_DEBUG_DATA_DUMP_16                (0x0364)
#define 	 SGMII_DEBUG_DATA_DUMP_17                (0x0368)
#define 	 SGMII_DEBUG_DATA_DUMP_18                (0x036c)
#define 	 SGMII_DEBUG_DATA_DUMP_19                (0x0370)
#define 	 SGMII_DEBUG_DATA_DUMP_20                (0x0374)
#define 	 SGMII_DEBUG_DATA_DUMP_21                (0x0378)
#define 	 SGMII_DEBUG_DATA_DUMP_22                (0x037c)
#define 	 SGMII_DEBUG_DATA_DUMP_23                (0x0380)
#define 	 SGMII_DEBUG_DATA_DUMP_24                (0x0384)
#define 	 SGMII_DEBUG_DATA_DUMP_25                (0x0388)
#define 	 SGMII_DEBUG_DATA_DUMP_26                (0x038c)
#define 	 SGMII_DEBUG_DATA_DUMP_27                (0x0390)
#define 	 SGMII_DEBUG_DATA_DUMP_28                (0x0394)
#define 	 SGMII_DEBUG_DATA_DUMP_29                (0x0398)
#define 	 SGMII_DEBUG_DATA_DUMP_30                (0x039c)
#define 	 SGMII_RG_HOST_CONTROL_1                 (0x03a0)
#define 	 SGMII_RG_HOST_CONTROL_2                 (0x03a4)
#define 	 SGMII_RG_IRQ_MASK                       (0x03a8)
#define 	 SGMII_RGS_IRQ_STATUS                    (0x03ac)
	
#endif //_SGMII_REG_H_
	
	


